import { writable, derived } from 'svelte/store';

// ── Gallery state ──────────────────────────────────────────────────────────
export const galleryImages  = writable([]);    // current browse results
export const galleryMode    = writable('grid'); // grid | table
export const selectedId     = writable(null);  // lightbox target image id (single click/open)
export const selectedItems  = writable(new Set()); // Set of selected image IDs
export const lastClickedId  = writable(null);  // for shift-click selection
export const galleryLoading = writable(false);
export const backendReady   = writable(false);

// ── Filters & sort ──────────────────────────────────────────────────────────
export const filters = writable({
  person:   '',
  tag:      '',
  scene:    '',
  folder:   '',
  path:     '',
  dateFrom: '',
  dateTo:   '',
});
export const sortBy   = writable('newest');  // newest | oldest | date_taken_desc | ...
export const thumbSize = writable(200);       // px; drives CSS var + API size param

// ── Sidebar view ─────────────────────────────────────────────────────────────
// 'all' | 'people' | 'tags' | 'dates' | 'process' | 'train' | 'settings'
export const sidebarView = writable('all');
export const sidebarCollapsed = writable(false);  // icon-only mode for small screens

// ── Auth ──────────────────────────────────────────────────────────────────────
export const currentUser = writable(null);   // { username, role } | null

// ── Processing ────────────────────────────────────────────────────────────────
export const processingJobs = writable([]);  // SSE batch jobs

// ── People ────────────────────────────────────────────────────────────────────
export const allPeople    = writable([]);
export const selectedPerson = writable(null);  // person object for detail view

// ── Stats ─────────────────────────────────────────────────────────────────────
export const stats = writable({});

// ── Model warm-up state ───────────────────────────────────────────────────────
export const modelReady = writable(false);

// ── Tags & scenes ─────────────────────────────────────────────────────────────
export const allTags   = writable([]);
export const allScenes = writable([]);

// ── i18n ──────────────────────────────────────────────────────────────────────
// English defaults so the UI is readable before the backend responds
const EN = {
  app_title: 'CrispLens', app_subtitle: 'AI-Powered Image and Face Recognition',
  version: 'Version', welcome: 'Welcome', logout: 'Logout', login: 'Login',
  details: 'Details', training_in_progress: 'Training',
  tab_recognize: 'Recognize', tab_train: 'Train', tab_people: 'People',
  tab_tags: 'Tags', tab_search: 'Search', tab_browse: 'Browse',
  tab_batch: 'Batch Process', tab_stats: 'Statistics', tab_settings: 'Settings',
  tab_admin: 'Admin', tab_export: 'Export', tab_timeline: 'Timeline', tab_folders: 'Folders',
  upload_image: 'Upload Image', upload_multiple: 'Upload Multiple Images',
  process_image: 'Process Image', processing: 'Processing...', detection_results: 'Detection Results',
  total_faces: 'Total Faces', known_people: 'Known People', unknown_people: 'Unknown People',
  ai_analysis: 'AI Analysis', description: 'Description', filename: 'Filename',
  scene_type: 'Scene Type', tags: 'Tags', confidence: 'Confidence', quality: 'Quality',
  date_created: 'Date Created', date_modified: 'Date Modified', camera_model: 'Camera Model',
  person_name: 'Person Name', training_images: 'Upload Training Images',
  training_method: 'Training Method', train_upload: 'Upload Images', train_folder: 'Scan Folder',
  folder_path: 'Folder Path', scan_folder: 'Scan Folder', train_system: 'Train System',
  training_complete: 'Training Complete!', training_failed: 'Training Failed',
  training_tips: 'Training Tips',
  search_description: 'Search for images containing specific people',
  search_button: 'Search', search_results: 'Search Results for',
  no_results_found: 'No results found', refresh: 'Refresh',
  browse_description: 'Browse all processed images', filter_options: 'Filter Options',
  filter_by_people: 'Filter by People', sort_by: 'Sort By',
  sort_newest: 'Newest first', sort_oldest: 'Oldest first',
  merge: 'Merge', select_all: 'Select All', deselect_all: 'Deselect All',
  batch_description: 'Process entire folders of images', select_folder: 'Select Folder',
  recursive_scan: 'Include Subfolders', process_folder: 'Process Folder',
  batch_progress: 'Progress', batch_complete: 'Batch Processing Complete!',
  processed: 'Processed', failed: 'Failed', skipped: 'Skipped', remaining: 'Remaining',
  stop_processing: 'Stop', resume_processing: 'Resume',
  stats_overview: 'Overview', stats_total_people: 'Total People', stats_total_images: 'Total Images',
  stats_total_faces: 'Total Faces Detected', stats_database: 'Database',
  refresh_stats: 'Refresh',
  settings_title: 'System Configuration', recognition_settings: 'Recognition Settings',
  backend: 'Backend', model: 'Model', detection_threshold: 'Detection Threshold',
  recognition_threshold: 'Recognition Threshold', use_gpu: 'Use GPU',
  ai_enrichment: 'AI Enrichment', enable_vlm: 'Enable VLM',
  vlm_provider: 'VLM Provider', vlm_api_key: 'API Key', vlm_model: 'Model',
  ui_settings: 'User Interface', language: 'Language',
  save_settings: 'Save Settings', reset_settings: 'Reset',
  user_management: 'User Management', username: 'Username', password: 'Password',
  role_admin: 'Administrator', role_user: 'User',
  no_image: 'Please upload an image', no_faces_detected: 'No faces detected',
  settings_saved: 'Settings saved', error: 'Error', success: 'Success',
  please_wait: 'Please wait...', loading: 'Loading...', no_key: 'No key set', of: 'of',
  ok: 'OK', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit',
  view: 'View', download: 'Download', upload: 'Upload', clear: 'Clear', reset: 'Reset',
  confirm: 'Confirm', back: 'Back', next: 'Next', previous: 'Previous',
  search_by_date: 'Date',
  change_password: 'Change Password',
  current_password: 'Current Password',
  new_password: 'New Password',
  confirm_password: 'Confirm Password',
  password_changed: 'Password changed successfully',
  set_password: 'Set Password',
  test_key: 'Test',
  key_valid: 'Key valid',
  key_invalid: 'Invalid key',
  // Cloud drives
  cloud_drives: 'Cloud Drives',
  add_drive: 'Add Drive',
  no_cloud_drives: 'No cloud drives configured',
  no_cloud_drives_hint: 'Add a network share or cloud storage account',
  drive_name: 'Drive Name', drive_type: 'Type', drive_host: 'Host', drive_server: 'Server',
  drive_share: 'Share', drive_username: 'Username', drive_password: 'Password',
  drive_domain: 'Domain', drive_port: 'Port', drive_remote_path: 'Remote Path',
  drive_ssh_key: 'SSH Key', drive_email: 'Email', drive_tfa: '2FA Code',
  drive_mount_point: 'Mount Point', drive_read_only: 'Read Only',
  drive_scope: 'Scope', drive_scope_system: 'System', drive_scope_user: 'Personal',
  drive_allowed_roles: 'Allowed Roles', drive_auto_mount: 'Auto-mount',
  drive_edit: 'Edit', drive_save: 'Save Drive', drive_delete: 'Delete Drive',
  drive_delete_confirm: 'Delete this drive?',
  drive_connect: 'Connect', drive_disconnect: 'Disconnect',
  drive_mount: 'Mount', drive_unmount: 'Unmount', drive_test: 'Test',
  drive_status_connected: 'Connected', drive_status_mounted: 'Mounted', drive_status_offline: 'Offline',
  drive_placeholder_name: 'My Drive', drive_placeholder_host: 'e.g. 192.168.1.1',
  drive_placeholder_server: '//server/share', drive_placeholder_share: 'share',
  drive_placeholder_remote_path: '/remote/path', drive_placeholder_ssh_key: '/path/to/key',
  drive_placeholder_tfa: '2FA code', drive_placeholder_mount_smb: '/mnt/smb',
  drive_placeholder_mount_sftp: '/mnt/sftp',
  // Face identification / clusters
  face_identification: 'Face Identification', face_clusters: 'Face Clusters',
  face_num: 'Face #', identify_persons: 'Identify',
  person_name_placeholder: 'Enter name…', type_name_placeholder: 'Type a name…',
  enter_person_name: 'Enter person name',
  all_faces_identified: 'All faces identified', no_faces_in_image: 'No faces in this image',
  no_clusters_found: 'No face clusters found', no_clusters_detail: 'Process more images to generate face clusters',
  clustering_faces: 'Clustering faces…', similarity_threshold: 'Similarity threshold',
  lower_threshold_hint: 'Lower threshold = more results',
  recognition_certainty: 'Certainty', conf_short: 'Conf',
  clear_all_identifications: 'Clear all identifications',
  drag_to_mark_face: 'Drag to mark a face',
  // Train
  browse_button: 'Browse', train_folder_description: 'Scan folder for named sub-folders (one per person)',
  // Sort options
  sort_date_taken_asc: 'Date taken (oldest)', sort_date_taken_desc: 'Date taken (newest)',
  sort_filename_az: 'Filename A–Z', sort_most_faces: 'Most faces',
  // Stats
  stats_images_with_date: 'Images with date',
  // Lightbox / image ops
  zoom_in: 'Zoom in', zoom_out: 'Zoom out', fit_to_screen: 'Fit to screen',
  press_esc_to_close: 'Press Esc to close', close: 'Close',
  run_detection: 'Run detection', remove_detection: 'Remove detection',
  run_vlm_only: 'Run VLM only',
  min_face_size: 'Min Face Size',
  // Detection model labels
  det_model_auto: 'Auto (default)',
  det_model_retinaface: 'RetinaFace',
  det_model_scrfd: 'SCRFD',
  det_model_yunet: 'YuNet',
  det_model_mediapipe: 'MediaPipe',
  det_model_none: 'None (VLM only)',
  // Generate / BFL
  gen_seed_random: 'random',
  // Misc
  apply: 'Apply', apply_to_all: 'Apply to all', apply_to_selected: 'Apply to selected',
  skip: 'Skip', rescan: 'Rescan', scanning: 'Scanning…', save_all: 'Save all',
  deselect: 'Deselect', selection: 'Selection', source: 'Source', target: 'Target',
  search_name: 'Search by name…', operation_cancelled: 'Cancelled',
  people_detected: 'People detected', process_more_images: 'Process more images',
  image_pending: '1 image pending', images_pending: '{n} images pending',
  // Events
  photo: 'photo', photos: 'photos', event_singular: 'event',
  events: 'Events', time_gap: 'Time gap:', grouping_by_time: 'Grouping by time…',
  no_events_found: 'No events found. Images may lack date metadata.',
  event_name_placeholder: 'Add event name…', open_event: 'Open event →',
  // Identify
  all_faces: 'All faces', no_images_with_faces: 'No images with detected faces.',
  // Watch Folders
  watch_folders: 'Watch Folders', wf_path_placeholder: 'Folder path…',
  add: 'Add', no_watch_folders: 'No watch folders yet.',
  no_watch_folders_sub: 'Add a folder above to automatically ingest new images.',
  recursive: 'Recursive', auto_scan_label: 'Auto-scan', every: 'Every',
  files_added_stat: 'added', last_scan_time: 'Last scan time',
  scan_complete_msg: 'Scan complete', scan_now: 'Scan Now', auto_scan_every: 'Auto-scan every',
  wf_already_watched: 'This folder is already being watched.',
  new_label: 'new', found_label: 'found', errors_label: 'errors',
  dismiss: 'Dismiss', images_added_count: 'images added.',
  // Duplicates
  duplicates: 'Duplicates', dup_method: 'Method',
  dup_method_name_size: 'Filename + Size', dup_method_hash: 'Binary hash (SHA256)',
  dup_method_visual: 'Visual (pHash)', dup_threshold: 'Threshold',
  dup_keep: 'Keep', dup_keep_most_faces: 'Most faces',
  dup_keep_oldest: 'Oldest file', dup_keep_largest: 'Largest file',
  dup_action: 'Action', dup_delete_from_disk: 'Delete from disk',
  dup_remove_db_only: 'Remove from DB only', dup_replace_symlink: 'Replace with symlink',
  dup_merge_faces: 'Merge face assignments', dup_resolve_selected: 'Resolve selected',
  dup_resolving: 'Resolving…', dup_resolved: '✓ Resolved', dup_resolve: 'Resolve',
  dup_role_guard: 'Resolving duplicates requires mediamanager or admin access',
  dup_view_only: 'View only', no_duplicates: 'No duplicates found with this method.',
  dup_run_scan_first: 'Run "Scan pHash" above first.',
  dup_copies: 'copies', dup_groups: 'groups', dup_keep_chip: '✓ Keep', dup_del_chip: 'Delete',
  computing_hashes: 'Computing hashes…',
  hash_scan_complete: 'Hash scan complete — duplicates updated',
  fill_hashes: 'Fill Hashes', scanning_phash: 'Scanning pHash…',
  scan_phash_btn: 'Scan pHash', phash_scan_complete: 'pHash scan complete',
  all_images_have_phash: 'All images have pHash',
  imagehash_not_installed: 'imagehash not installed on the server.',
  recoverable: 'recoverable',
  cleanup_source_files: 'Clean up source files',
  cleanup_originals_hint: 'These originals live outside the server copy — the server-side file was already handled. Choose what to do with the originals on their source machine:',
  cleanup_action: 'Action', cleanup_trash_opt: 'Move to Trash (reversible)',
  cleanup_delete_opt: 'Delete permanently',
  cleanup_symlink_opt: 'Replace with symlink to kept file',
  download_script: 'Download script', review_before_run: 'Review before running',
  delete_via_browser: 'Delete via browser',
  browser_local_only: 'Grants per-folder permission — local files only',
  move_to_trash: 'Move to Trash',
  sends_to_os_trash: 'Sends files to your OS Trash (reversible)',
  download_json_list: 'Download JSON list',
  import_to_local: 'Import into your local Electron client to trash files there',
  import_cleanup_json: 'Import cleanup JSON',
  execute_downloaded_json: 'Execute a previously downloaded cleanup JSON on this machine',
  by_name_size: 'By name+size:', by_hash: 'By hash:', stat_visual: 'Visual:',
  wasted: 'Wasted:', origin_label: 'origin:',
  // Filesystem
  fs_server_mode: 'Server', fs_local_mode: 'Local', fs_cloud_mode: 'Cloud',
  select_drive_below: 'Select a drive below',
  fs_in_db: 'In DB', fs_not_in_db: 'Not in DB', fs_no_images: 'no images',
  fs_folder_label: 'folder', fs_image_label: 'image', fs_file_label: 'file',
  fs_empty_folder: 'This folder is empty.',
  fs_name_col: 'Name', fs_status_col: 'Status', fs_size_col: 'Size',
  fs_fetching: 'Fetching', fs_uploading: 'Uploading', fs_adding: 'Adding',
  fs_images_only: '(images only)', fs_images_folders: '(images + folders)',
  fs_already_in_db: 'already in DB.', fs_go: 'Go', fs_path_placeholder: 'Enter path…',
  fs_select_cloud_drive: 'Select a cloud or network drive to browse:',
  fs_no_cloud_drives_fs: 'No cloud drives configured.',
  fs_add_in_settings: 'Add drives in Settings → Cloud Drives.',
  fs_grant_access: 'Grant access to folder…',
  fs_pick_local_folder: 'Pick a local folder — the browser will ask for permission to read it.',
  fs_select_images: 'Select images…', fs_select_folder_btn: 'Select folder…',
  fs_rename: 'Rename', fs_trash: 'Trash', fs_loading_drives: 'Loading drives…',
  fs_not_connected: 'Not connected — connect in Cloud Drives first',
  fs_add_to_db: 'Add to DB', fs_add_to_db_cloud: 'Add to DB from cloud',
  fs_upload_to_db: 'Upload to DB', fs_shared: 'Shared', fs_private: 'Private',
  fs_select_drive_to_add: 'select images or folders to add to DB',
  fs_upload_to_server: 'select images to upload to server DB',
  fs_change_folder: 'Change folder…',
  fs_local_folder_hint: 'Local folder — click "Grant access" to browse your device',
  fs_local_upload_hint: 'Local upload — pick images or a folder from your device',
  // Context menu
  ctx_open_external: 'Open file', ctx_open_folder: 'Open folder',
  ctx_browse_folder: 'Browse folder', ctx_add_to_album: 'Add to Album',
  ctx_no_albums: 'No albums — create one first', ctx_new_album: '+ New album…',
  ctx_people_in_image: 'People in this image', ctx_all_photos_of: 'All photos of',
  ctx_crop_image: 'Crop image', ctx_adjust_image: 'Adjust image',
  ctx_convert_export: 'Convert / Export', ctx_download_file: 'Download file',
  ctx_copy_path: 'Copy file path',
  // Convert modal
  conv_format: 'Format', conv_quality: 'Quality', conv_resize: 'Resize',
  conv_no_resize: 'No resize', conv_fit: 'Fit within (keep ratio)',
  conv_exact: 'Exact dimensions', conv_max_size: 'Max size', conv_save_as: 'Save as',
  conv_replace_orig: 'Replace original', conv_new_file: 'New file',
  conv_output_folder: 'Output folder', conv_suffix: 'Suffix', conv_folder: 'Folder',
  conv_done: 'Done', conv_converting: 'Converting…', conv_convert: 'Convert',
  // Adjust modal
  adj_input_levels: 'Input Levels', adj_output: 'Output', adj_presets: 'Presets',
  adj_light: 'Light', adj_brightness: 'Brightness', adj_contrast: 'Contrast',
  adj_colour: 'Colour', adj_saturation: 'Saturation', adj_warmth: 'Warmth',
  adj_detail: 'Detail', adj_sharpness: 'Sharpness', adj_save_as: 'Save as',
  adj_replace_orig: 'Replace original', adj_new_file: 'New file', adj_suffix: 'Suffix',
  adj_applying: 'Applying…', adj_reset_all: 'Reset All', adj_saved: '✓ Saved',
  selected_label: 'selected',
  // BFL AI editing
  bfl_outpaint: 'Outpaint', bfl_inpaint: 'Inpaint', bfl_ai_edit: 'AI Edit',
  bfl_add_top: 'Add Top', bfl_add_bottom: 'Add Bottom',
  bfl_add_left: 'Add Left', bfl_add_right: 'Add Right',
  bfl_mask_x: 'Mask X', bfl_mask_y: 'Mask Y',
  bfl_mask_w: 'Mask W', bfl_mask_h: 'Mask H',
  bfl_prompt_optional: 'Prompt (optional)',
  bfl_edit_prompt: 'Describe the edit…',
  bfl_inpaint_prompt: 'What to generate in the masked area…',
  bfl_model: 'Model',
  bfl_applying: 'Generating…', bfl_done: '✓ Generated',
  bfl_no_key: 'BFL API key not configured — add it in Settings → API Keys',
  ctx_ai_edit: 'AI Edit (BFL)',
  conv_resize_outpaint: 'Outpaint (AI)',
  bfl_generate: 'Generate',
  bfl_gen_prompt: 'Describe what to generate…',
  bfl_aspect_ratio: 'Aspect ratio',
  bfl_output_folder: 'Output folder',
  bfl_filename_prefix: 'Filename prefix',
  bfl_gen_hint: 'Thumbnail shown for reference — not sent to the model',
  bfl_gen_hint_include: 'Thumbnail shown for reference — will be sent as input image',
  bfl_include_ref_image: 'Include as reference image (input_image)',
  bfl_width: 'Width (px)',
  bfl_height: 'Height (px)',
  bfl_steps: 'Steps',
  bfl_guidance: 'Guidance',
  bfl_seed: 'Seed',
  bfl_zoom: 'Zoom',
  bfl_drag_hint: 'Drag edges to set border size',
  bfl_mask_hint: 'Drag to position the fill area',
  // Sidebar nav labels
  tab_albums: 'Albums',
  tab_events: 'Events',
  tab_identify: 'Identify',
  tab_faceclusters: 'Face Clusters',
  tab_filesystem: 'Filesystem',
  tab_watchfolders: 'Watch Folders',
  tab_duplicates: 'Duplicates',
  tab_ingest: 'Ingest',
  sidebar_expand: 'Expand sidebar',
  sidebar_collapse: 'Collapse sidebar',
  // Crop / Canvas Size modal
  tab_generate: 'Generate',
  crop_image: 'Crop Image',
  canvas_size: 'Canvas Size',
  crop_aspect_ratio: 'Aspect ratio',
  crop_selection_px: 'Selection (px)',
  crop_reset: '↺ Reset',
  crop_filename_hint: 'Filename (auto if blank)',
  crop_and_save: 'Crop & Save',
  saving: 'Saving…',
  save_as: 'Save as',
  save_as_replace: 'Replace original',
  save_as_new_file: 'New file',
  canvas_add_border: 'Add border (px)',
  canvas_fill_mode: 'Fill mode',
  canvas_fill_solid: 'Solid color',
  canvas_fill_mirror: 'Mirror edge',
  canvas_fill_outpaint: 'AI Outpaint',
  canvas_fill_outpaint_hint: 'Will open AI Edit → Outpaint tab',
  canvas_apply: 'Apply Canvas Size',
  // Generate view
  gen_image_title: 'Generate Image',
  gen_model_label: 'Model',
  gen_prompt_label: 'Prompt',
  gen_prompt_placeholder: 'Describe what to generate…',
  gen_filename_prefix: 'Filename prefix',
  gen_output_folder: 'Output folder (optional)',
  gen_output_folder_hint: 'Leave blank to use default generated/ folder',
  gen_result_title: 'Generated Image',
  gen_view_in_gallery: 'View in gallery',
  gen_generating: 'Generating…',
  // Done-panel actions (shared between AIEditModal and GenerateView)
  done_without_db: 'Without DB',
  done_view_raw: 'View (no DB)',
  done_download_raw: 'Download (no DB)',
  done_save_to_db: 'Save to DB',
  done_save_only: 'Save only',
  done_save_gallery_title: 'Register in DB and open in gallery',
  done_save_lightbox_title: 'Register in DB and open image',
  done_save_silent_title: 'Register in DB and close',
  done_generate_another: 'Generate another',
  // Detection model selector (shared)
  rescan_mode_both: 'Both', rescan_mode_faces: 'Faces', rescan_mode_vlm: 'VLM',
  also_run_vlm: 'Also refresh VLM',
  // Admin — server management
  admin_server_mgmt:   'Server Management',
  admin_update_server: 'Update Server',
  admin_view_logs:     'View Logs',
  admin_run_update:    'Run Update',
  update_modal_hint:   'This will run fix_db.sh as root (git pull + DB migrations + service restart). The connection will drop when the server restarts.',
  root_password:       'Root password',
  running:             'Running…',
  admin_logs_title:    'Server Logs',
  logs_refresh:        'Refresh',
  logs_follow:         'Follow',
  logs_path:           'Log file',
  // Admin — copy-exempt paths
  exempt_paths_label:  'Copy-exempt server paths',
  exempt_paths_hint:   'Files uploaded from these server paths are recorded in-place (no copy to uploads/).',
  fix_db_path_label:   'fix_db.sh path',
  fix_db_path_hint:    'Full path to fix_db.sh on the server.',
};

export const TRANSLATIONS = {
  en: EN,
  de: {
    app_title: 'CrispLens', app_subtitle: 'KI-gestützte Bild- und Gesichtserkennung',
    version: 'Version', welcome: 'Willkommen', logout: 'Abmelden', login: 'Anmelden',
    details: 'Details', training_in_progress: 'Training',
    tab_recognize: 'Erkennen', tab_train: 'Trainieren', tab_people: 'Personen',
    tab_tags: 'Tags', tab_search: 'Suchen', tab_browse: 'Durchsuchen',
    tab_batch: 'Stapelverarbeitung', tab_stats: 'Statistiken', tab_settings: 'Einstellungen',
    tab_admin: 'Admin', tab_export: 'Export', tab_timeline: 'Zeitleiste', tab_folders: 'Ordner',
    upload_image: 'Bild hochladen', upload_multiple: 'Mehrere Bilder hochladen',
    process_image: 'Bild verarbeiten', processing: 'Verarbeitung...', detection_results: 'Erkennungsergebnisse',
    total_faces: 'Gesichter gesamt', known_people: 'Bekannte Personen', unknown_people: 'Unbekannte Personen',
    ai_analysis: 'KI-Analyse', description: 'Beschreibung', filename: 'Dateiname',
    scene_type: 'Szenentyp', tags: 'Tags', confidence: 'Konfidenz', quality: 'Qualität',
    date_created: 'Erstellungsdatum', date_modified: 'Änderungsdatum', camera_model: 'Kameramodell',
    person_name: 'Personenname', training_images: 'Trainingsbilder hochladen',
    training_method: 'Trainingsmethode', train_upload: 'Bilder hochladen', train_folder: 'Ordner scannen',
    folder_path: 'Ordnerpfad', scan_folder: 'Ordner scannen', train_system: 'System trainieren',
    training_complete: 'Training abgeschlossen!', training_failed: 'Training fehlgeschlagen',
    training_tips: 'Trainingshinweise',
    search_description: 'Bilder mit bestimmten Personen suchen',
    search_button: 'Suchen', search_results: 'Suchergebnisse für',
    no_results_found: 'Keine Ergebnisse gefunden', refresh: 'Aktualisieren',
    browse_description: 'Alle verarbeiteten Bilder durchsuchen', filter_options: 'Filteroptionen',
    filter_by_people: 'Nach Personen filtern', sort_by: 'Sortieren nach',
    sort_newest: 'Neueste zuerst', sort_oldest: 'Älteste zuerst',
    merge: 'Zusammenführen', select_all: 'Alle auswählen', deselect_all: 'Auswahl aufheben',
    batch_description: 'Gesamte Ordner verarbeiten', select_folder: 'Ordner wählen',
    recursive_scan: 'Unterordner einschließen', process_folder: 'Ordner verarbeiten',
    batch_progress: 'Fortschritt', batch_complete: 'Stapelverarbeitung abgeschlossen!',
    processed: 'Verarbeitet', failed: 'Fehlgeschlagen', skipped: 'Übersprungen', remaining: 'Verbleibend',
    stop_processing: 'Stopp', resume_processing: 'Fortsetzen',
    stats_overview: 'Übersicht', stats_total_people: 'Personen gesamt', stats_total_images: 'Bilder gesamt',
    stats_total_faces: 'Erkannte Gesichter', stats_database: 'Datenbank',
    refresh_stats: 'Aktualisieren',
    settings_title: 'Systemkonfiguration', recognition_settings: 'Erkennungseinstellungen',
    backend: 'Backend', model: 'Modell', detection_threshold: 'Erkennungsschwelle',
    recognition_threshold: 'Erkennungsschwellwert', use_gpu: 'GPU verwenden',
    ai_enrichment: 'KI-Anreicherung', enable_vlm: 'VLM aktivieren',
    vlm_provider: 'VLM-Anbieter', vlm_api_key: 'API-Schlüssel', vlm_model: 'Modell',
    ui_settings: 'Benutzeroberfläche', language: 'Sprache',
    save_settings: 'Einstellungen speichern', reset_settings: 'Zurücksetzen',
    user_management: 'Benutzerverwaltung', username: 'Benutzername', password: 'Passwort',
    role_admin: 'Administrator', role_user: 'Benutzer',
    no_image: 'Bitte ein Bild hochladen', no_faces_detected: 'Keine Gesichter erkannt',
    settings_saved: 'Einstellungen gespeichert', error: 'Fehler', success: 'Erfolg',
    please_wait: 'Bitte warten...', loading: 'Lädt...', no_key: 'Kein Schlüssel', of: 'von',
    ok: 'OK', cancel: 'Abbrechen', save: 'Speichern', delete: 'Löschen', edit: 'Bearbeiten',
    view: 'Ansehen', download: 'Herunterladen', upload: 'Hochladen', clear: 'Leeren', reset: 'Zurücksetzen',
    confirm: 'Bestätigen', back: 'Zurück', next: 'Weiter', previous: 'Zurück',
    search_by_date: 'Datum',
    change_password: 'Passwort ändern',
    current_password: 'Aktuelles Passwort',
    new_password: 'Neues Passwort',
    confirm_password: 'Passwort bestätigen',
    password_changed: 'Passwort erfolgreich geändert',
    set_password: 'Passwort setzen',
    test_key: 'Testen',
    key_valid: 'Schlüssel gültig',
    key_invalid: 'Ungültiger Schlüssel',
    // Cloud drives
    cloud_drives: 'Cloud-Laufwerke',
    add_drive: 'Laufwerk hinzufügen',
    no_cloud_drives: 'Keine Cloud-Laufwerke konfiguriert',
    no_cloud_drives_hint: 'Netzwerkfreigabe oder Cloud-Konto hinzufügen',
    drive_name: 'Laufwerkname', drive_type: 'Typ', drive_host: 'Host', drive_server: 'Server',
    drive_share: 'Freigabe', drive_username: 'Benutzername', drive_password: 'Passwort',
    drive_domain: 'Domäne', drive_port: 'Port', drive_remote_path: 'Entfernter Pfad',
    drive_ssh_key: 'SSH-Schlüssel', drive_email: 'E-Mail', drive_tfa: '2FA-Code',
    drive_mount_point: 'Einhängepunkt', drive_read_only: 'Nur lesen',
    drive_scope: 'Bereich', drive_scope_system: 'System', drive_scope_user: 'Persönlich',
    drive_allowed_roles: 'Erlaubte Rollen', drive_auto_mount: 'Automatisch einbinden',
    drive_edit: 'Bearbeiten', drive_save: 'Laufwerk speichern', drive_delete: 'Laufwerk löschen',
    drive_delete_confirm: 'Laufwerk löschen?',
    drive_connect: 'Verbinden', drive_disconnect: 'Trennen',
    drive_mount: 'Einbinden', drive_unmount: 'Trennen', drive_test: 'Testen',
    drive_status_connected: 'Verbunden', drive_status_mounted: 'Eingebunden', drive_status_offline: 'Offline',
    drive_placeholder_name: 'Mein Laufwerk', drive_placeholder_host: 'z.B. 192.168.1.1',
    drive_placeholder_server: '//server/freigabe', drive_placeholder_share: 'freigabe',
    drive_placeholder_remote_path: '/entfernter/pfad', drive_placeholder_ssh_key: '/pfad/zum/schlüssel',
    drive_placeholder_tfa: '2FA-Code', drive_placeholder_mount_smb: '/mnt/smb',
    drive_placeholder_mount_sftp: '/mnt/sftp',
    // Face identification / clusters
    face_identification: 'Gesichtserkennung', face_clusters: 'Gesichtsgruppen',
    face_num: 'Gesicht #', identify_persons: 'Identifizieren',
    person_name_placeholder: 'Name eingeben…', type_name_placeholder: 'Name eingeben…',
    enter_person_name: 'Personenname eingeben',
    all_faces_identified: 'Alle Gesichter identifiziert', no_faces_in_image: 'Keine Gesichter in diesem Bild',
    no_clusters_found: 'Keine Gesichtsgruppen gefunden', no_clusters_detail: 'Weitere Bilder verarbeiten um Gesichtsgruppen zu erstellen',
    clustering_faces: 'Gesichter werden gruppiert…', similarity_threshold: 'Ähnlichkeitsschwelle',
    lower_threshold_hint: 'Niedrigerer Schwellwert = mehr Ergebnisse',
    recognition_certainty: 'Gewissheit', conf_short: 'Konf',
    clear_all_identifications: 'Alle Identifikationen löschen',
    drag_to_mark_face: 'Ziehen um Gesicht zu markieren',
    // Train
    browse_button: 'Durchsuchen', train_folder_description: 'Ordner mit benannten Unterordnern (je eine Person)',
    // Sort options
    sort_date_taken_asc: 'Aufnahmedatum (älteste)', sort_date_taken_desc: 'Aufnahmedatum (neueste)',
    sort_filename_az: 'Dateiname A–Z', sort_most_faces: 'Meiste Gesichter',
    // Stats
    stats_images_with_date: 'Bilder mit Datum',
    // Lightbox / image ops
    zoom_in: 'Vergrößern', zoom_out: 'Verkleinern', fit_to_screen: 'Bildschirm füllen',
    press_esc_to_close: 'Esc zum Schließen', close: 'Schließen',
    run_detection: 'Erkennung starten', remove_detection: 'Erkennung entfernen',
    run_vlm_only: 'Nur VLM ausführen',
    min_face_size: 'Min. Gesichtsgröße',
    // Detection model labels
    det_model_auto: 'Auto (Standard)',
    det_model_retinaface: 'RetinaFace',
    det_model_scrfd: 'SCRFD',
    det_model_yunet: 'YuNet',
    det_model_mediapipe: 'MediaPipe',
    det_model_none: 'Keines (nur VLM)',
    // Generate / BFL
    gen_seed_random: 'zufällig',
    // Misc
    apply: 'Anwenden', apply_to_all: 'Auf alle anwenden', apply_to_selected: 'Auf Auswahl anwenden',
    skip: 'Überspringen', rescan: 'Neu scannen', scanning: 'Scannt…', save_all: 'Alle speichern',
    deselect: 'Auswahl aufheben', selection: 'Auswahl', source: 'Quelle', target: 'Ziel',
    search_name: 'Nach Name suchen…', operation_cancelled: 'Abgebrochen',
    people_detected: 'Erkannte Personen', process_more_images: 'Weitere Bilder verarbeiten',
    image_pending: '1 Bild ausstehend', images_pending: '{n} Bilder ausstehend',
    // Events
    photo: 'Foto', photos: 'Fotos', event_singular: 'Ereignis',
    events: 'Ereignisse', time_gap: 'Zeitabstand:', grouping_by_time: 'Gruppiere nach Zeit…',
    no_events_found: 'Keine Ereignisse gefunden. Bilder haben möglicherweise keine Datumsmetadaten.',
    event_name_placeholder: 'Ereignisname hinzufügen…', open_event: 'Ereignis öffnen →',
    // Identify
    all_faces: 'Alle Gesichter', no_images_with_faces: 'Keine Bilder mit erkannten Gesichtern.',
    // Watch Folders
    watch_folders: 'Überwachte Ordner', wf_path_placeholder: 'Ordnerpfad…',
    add: 'Hinzufügen', no_watch_folders: 'Noch keine überwachten Ordner.',
    no_watch_folders_sub: 'Oben einen Ordner hinzufügen, um neue Bilder automatisch einzulesen.',
    recursive: 'Rekursiv', auto_scan_label: 'Auto-Scan', every: 'Alle',
    files_added_stat: 'hinzugefügt', last_scan_time: 'Letzter Scan',
    scan_complete_msg: 'Scan abgeschlossen', scan_now: 'Jetzt scannen', auto_scan_every: 'Auto-Scan alle',
    wf_already_watched: 'Dieser Ordner wird bereits überwacht.',
    new_label: 'neu', found_label: 'gefunden', errors_label: 'Fehler',
    dismiss: 'Schließen', images_added_count: 'Bilder hinzugefügt.',
    // Duplicates
    duplicates: 'Duplikate', dup_method: 'Methode',
    dup_method_name_size: 'Dateiname + Größe', dup_method_hash: 'Binärer Hash (SHA256)',
    dup_method_visual: 'Visuell (pHash)', dup_threshold: 'Schwellwert',
    dup_keep: 'Behalten', dup_keep_most_faces: 'Meiste Gesichter',
    dup_keep_oldest: 'Älteste Datei', dup_keep_largest: 'Größte Datei',
    dup_action: 'Aktion', dup_delete_from_disk: 'Von Disk löschen',
    dup_remove_db_only: 'Nur aus DB entfernen', dup_replace_symlink: 'Durch Symlink ersetzen',
    dup_merge_faces: 'Gesichtszuweisungen zusammenführen', dup_resolve_selected: 'Ausgewählte auflösen',
    dup_resolving: 'Wird aufgelöst…', dup_resolved: '✓ Aufgelöst', dup_resolve: 'Auflösen',
    dup_role_guard: 'Duplikatauflösung erfordert Mediamanager- oder Admin-Zugriff',
    dup_view_only: 'Nur ansehen', no_duplicates: 'Keine Duplikate mit dieser Methode gefunden.',
    dup_run_scan_first: '"pHash scannen" oben zuerst ausführen.',
    dup_copies: 'Kopien', dup_groups: 'Gruppen', dup_keep_chip: '✓ Behalten', dup_del_chip: 'Löschen',
    computing_hashes: 'Berechne Hashes…',
    hash_scan_complete: 'Hash-Scan abgeschlossen — Duplikate aktualisiert',
    fill_hashes: 'Hashes befüllen', scanning_phash: 'Scanne pHash…',
    scan_phash_btn: 'pHash scannen', phash_scan_complete: 'pHash-Scan abgeschlossen',
    all_images_have_phash: 'Alle Bilder haben pHash',
    imagehash_not_installed: 'imagehash nicht auf dem Server installiert.',
    recoverable: 'rückgewinnbar',
    cleanup_source_files: 'Quelldateien bereinigen',
    cleanup_originals_hint: 'Diese Originale befinden sich außerhalb der Serverkopie — die serverseitige Datei wurde bereits behandelt. Wählen Sie, was mit den Originalen auf dem Quellrechner geschehen soll:',
    cleanup_action: 'Aktion', cleanup_trash_opt: 'In Papierkorb verschieben (reversibel)',
    cleanup_delete_opt: 'Dauerhaft löschen',
    cleanup_symlink_opt: 'Durch Symlink auf behaltene Datei ersetzen',
    download_script: 'Skript herunterladen', review_before_run: 'Vor der Ausführung prüfen',
    delete_via_browser: 'Über Browser löschen',
    browser_local_only: 'Erteilt Ordner-Berechtigung — nur lokale Dateien',
    move_to_trash: 'In Papierkorb verschieben',
    sends_to_os_trash: 'Verschiebt Dateien in den OS-Papierkorb (reversibel)',
    download_json_list: 'JSON-Liste herunterladen',
    import_to_local: 'In lokalen Electron-Client importieren, um Dateien dort zu entfernen',
    import_cleanup_json: 'Bereinigung-JSON importieren',
    execute_downloaded_json: 'Zuvor heruntergeladene Bereinigung-JSON auf diesem Rechner ausführen',
    by_name_size: 'Nach Name+Größe:', by_hash: 'Nach Hash:', stat_visual: 'Visuell:',
    wasted: 'Verschwendet:', origin_label: 'Herkunft:',
    // Filesystem
    fs_server_mode: 'Server', fs_local_mode: 'Lokal', fs_cloud_mode: 'Cloud',
    select_drive_below: 'Unten ein Laufwerk auswählen',
    fs_in_db: 'In DB', fs_not_in_db: 'Nicht in DB', fs_no_images: 'keine Bilder',
    fs_folder_label: 'Ordner', fs_image_label: 'Bild', fs_file_label: 'Datei',
    fs_empty_folder: 'Dieser Ordner ist leer.',
    fs_name_col: 'Name', fs_status_col: 'Status', fs_size_col: 'Größe',
    fs_fetching: 'Wird abgerufen', fs_uploading: 'Wird hochgeladen', fs_adding: 'Wird hinzugefügt',
    fs_images_only: '(nur Bilder)', fs_images_folders: '(Bilder + Ordner)',
    fs_already_in_db: 'bereits in DB.', fs_go: 'Los', fs_path_placeholder: 'Pfad eingeben…',
    fs_select_cloud_drive: 'Cloud- oder Netzlaufwerk zum Durchsuchen auswählen:',
    fs_no_cloud_drives_fs: 'Keine Cloud-Laufwerke konfiguriert.',
    fs_add_in_settings: 'Laufwerke in Einstellungen → Cloud-Laufwerke hinzufügen.',
    fs_grant_access: 'Zugriff auf Ordner gewähren…',
    fs_pick_local_folder: 'Lokalen Ordner auswählen — der Browser fragt nach Berechtigung.',
    fs_select_images: 'Bilder auswählen…', fs_select_folder_btn: 'Ordner auswählen…',
    fs_rename: 'Umbenennen', fs_trash: 'Papierkorb', fs_loading_drives: 'Laufwerke laden…',
    fs_not_connected: 'Nicht verbunden — zuerst in Cloud-Laufwerken verbinden',
    fs_add_to_db: 'Zur DB hinzufügen', fs_add_to_db_cloud: 'Von Cloud zur DB hinzufügen',
    fs_upload_to_db: 'Zur DB hochladen', fs_shared: 'Geteilt', fs_private: 'Privat',
    fs_select_drive_to_add: 'Bilder oder Ordner auswählen, um zur DB hinzuzufügen',
    fs_upload_to_server: 'Bilder hochladen, um sie zur Server-DB hinzuzufügen',
    fs_change_folder: 'Ordner ändern…',
    fs_local_folder_hint: 'Lokaler Ordner — "Zugriff gewähren" klicken, um Gerät zu durchsuchen',
    fs_local_upload_hint: 'Lokales Hochladen — Bilder oder Ordner vom Gerät auswählen',
    // Context menu
    ctx_open_external: 'Datei öffnen', ctx_open_folder: 'Ordner öffnen',
    ctx_browse_folder: 'Ordner durchsuchen', ctx_add_to_album: 'Zum Album hinzufügen',
    ctx_no_albums: 'Keine Alben — erst eines erstellen', ctx_new_album: '+ Neues Album…',
    ctx_people_in_image: 'Personen in diesem Bild', ctx_all_photos_of: 'Alle Fotos von',
    ctx_crop_image: 'Bild zuschneiden', ctx_adjust_image: 'Bild anpassen',
    ctx_convert_export: 'Konvertieren / Exportieren', ctx_download_file: 'Datei herunterladen',
    ctx_copy_path: 'Dateipfad kopieren',
    // Convert modal
    conv_format: 'Format', conv_quality: 'Qualität', conv_resize: 'Skalieren',
    conv_no_resize: 'Keine Skalierung', conv_fit: 'Einpassen (Seitenverhältnis beibehalten)',
    conv_exact: 'Genaue Abmessungen', conv_max_size: 'Maximale Größe', conv_save_as: 'Speichern als',
    conv_replace_orig: 'Original ersetzen', conv_new_file: 'Neue Datei',
    conv_output_folder: 'Ausgabeordner', conv_suffix: 'Suffix', conv_folder: 'Ordner',
    conv_done: 'Fertig', conv_converting: 'Konvertiere…', conv_convert: 'Konvertieren',
    // Adjust modal
    adj_input_levels: 'Eingabepegel', adj_output: 'Ausgabe', adj_presets: 'Voreinstellungen',
    adj_light: 'Licht', adj_brightness: 'Helligkeit', adj_contrast: 'Kontrast',
    adj_colour: 'Farbe', adj_saturation: 'Sättigung', adj_warmth: 'Wärme',
    adj_detail: 'Detail', adj_sharpness: 'Schärfe', adj_save_as: 'Speichern als',
    adj_replace_orig: 'Original ersetzen', adj_new_file: 'Neue Datei', adj_suffix: 'Suffix',
    adj_applying: 'Wird angewendet…', adj_reset_all: 'Alles zurücksetzen', adj_saved: '✓ Gespeichert',
    selected_label: 'ausgewählt',
    // BFL AI-Bildbearbeitung
    bfl_outpaint: 'Ausmalen', bfl_inpaint: 'Einmalen', bfl_ai_edit: 'KI-Bearbeitung',
    bfl_add_top: 'Oben hinzufügen', bfl_add_bottom: 'Unten hinzufügen',
    bfl_add_left: 'Links hinzufügen', bfl_add_right: 'Rechts hinzufügen',
    bfl_mask_x: 'Maske X', bfl_mask_y: 'Maske Y',
    bfl_mask_w: 'Maske Breite', bfl_mask_h: 'Maske Höhe',
    bfl_prompt_optional: 'Prompt (optional)',
    bfl_edit_prompt: 'Bearbeitung beschreiben…',
    bfl_inpaint_prompt: 'Was im markierten Bereich erzeugen…',
    bfl_model: 'Modell',
    bfl_applying: 'Wird generiert…', bfl_done: '✓ Generiert',
    bfl_no_key: 'BFL-API-Schlüssel fehlt — in Einstellungen → API-Schlüssel hinzufügen',
    ctx_ai_edit: 'KI-Bearbeitung (BFL)',
    conv_resize_outpaint: 'Ausmalen (KI)',
    bfl_generate: 'Generieren',
    bfl_gen_prompt: 'Was generiert werden soll…',
    bfl_aspect_ratio: 'Seitenverhältnis',
    bfl_output_folder: 'Ausgabeordner',
    bfl_filename_prefix: 'Dateinamen-Präfix',
    bfl_gen_hint: 'Vorschau nur zur Referenz — wird nicht an das Modell gesendet',
    bfl_gen_hint_include: 'Vorschau — wird als Eingabebild gesendet',
    bfl_include_ref_image: 'Als Referenzbild einschließen (input_image)',
    bfl_width: 'Breite (px)',
    bfl_height: 'Höhe (px)',
    bfl_steps: 'Schritte',
    bfl_guidance: 'Führung',
    bfl_seed: 'Zufallswert',
    bfl_zoom: 'Zoom',
    bfl_drag_hint: 'Ränder ziehen um Randgröße festzulegen',
    bfl_mask_hint: 'Ziehen um den Füllbereich zu positionieren',
    // Sidebar nav labels
    tab_albums: 'Alben',
    tab_events: 'Ereignisse',
    tab_identify: 'Identifizieren',
    tab_faceclusters: 'Gesichtsgruppen',
    tab_filesystem: 'Dateisystem',
    tab_watchfolders: 'Überwachte Ordner',
    tab_duplicates: 'Duplikate',
    tab_ingest: 'Import',
    sidebar_expand: 'Seitenleiste ausklappen',
    sidebar_collapse: 'Seitenleiste einklappen',
    // Crop / Canvas Size modal
    tab_generate: 'Generieren',
    crop_image: 'Bild zuschneiden',
    canvas_size: 'Leinwandgröße',
    crop_aspect_ratio: 'Seitenverhältnis',
    crop_selection_px: 'Auswahl (px)',
    crop_reset: '↺ Zurücksetzen',
    crop_filename_hint: 'Dateiname (leer = automatisch)',
    crop_and_save: 'Zuschneiden & Speichern',
    saving: 'Speichern…',
    save_as: 'Speichern als',
    save_as_replace: 'Original ersetzen',
    save_as_new_file: 'Neue Datei',
    canvas_add_border: 'Rand hinzufügen (px)',
    canvas_fill_mode: 'Füllmodus',
    canvas_fill_solid: 'Volltonfarbe',
    canvas_fill_mirror: 'Randpixel spiegeln',
    canvas_fill_outpaint: 'KI-Outpaint',
    canvas_fill_outpaint_hint: 'Öffnet KI-Bearbeitung → Outpaint-Tab',
    canvas_apply: 'Leinwandgröße anwenden',
    // Generate view
    gen_image_title: 'Bild generieren',
    gen_model_label: 'Modell',
    gen_prompt_label: 'Prompt',
    gen_prompt_placeholder: 'Was generiert werden soll…',
    gen_filename_prefix: 'Dateinamen-Präfix',
    gen_output_folder: 'Ausgabeordner (optional)',
    gen_output_folder_hint: 'Leer lassen für Standard-Ordner generated/',
    gen_result_title: 'Generiertes Bild',
    gen_view_in_gallery: 'In Galerie ansehen',
    gen_generating: 'Wird generiert…',
    // Done-panel actions (shared between AIEditModal and GenerateView)
    done_without_db: 'Ohne DB',
    done_view_raw: 'Ansehen (kein DB)',
    done_download_raw: 'Download (kein DB)',
    done_save_to_db: 'In DB speichern',
    done_save_only: 'Nur speichern',
    done_save_gallery_title: 'In DB eintragen und in Galerie anzeigen',
    done_save_lightbox_title: 'In DB eintragen und Bild öffnen',
    done_save_silent_title: 'In DB eintragen und schließen',
    done_generate_another: 'Nochmals generieren',
    // Detection model selector (shared)
    rescan_mode_both: 'Beides', rescan_mode_faces: 'Gesichter', rescan_mode_vlm: 'VLM',
    also_run_vlm: 'Auch VLM aktualisieren',
    // Admin — server management
    admin_server_mgmt:   'Server-Verwaltung',
    admin_update_server: 'Server aktualisieren',
    admin_view_logs:     'Logs anzeigen',
    admin_run_update:    'Update starten',
    update_modal_hint:   'Führt fix_db.sh als root aus (git pull + DB-Migrationen + Neustart). Die Verbindung wird beim Neustart unterbrochen.',
    root_password:       'Root-Passwort',
    running:             'Läuft…',
    admin_logs_title:    'Server-Logs',
    logs_refresh:        'Aktualisieren',
    logs_follow:         'Folgen',
    logs_path:           'Log-Datei',
    // Admin — copy-exempt paths
    exempt_paths_label:  'Kopier-Ausnahmepfade',
    exempt_paths_hint:   'Dateien von diesen Server-Pfaden werden direkt in der DB registriert (keine Kopie nach uploads/).',
    fix_db_path_label:   'fix_db.sh Pfad',
    fix_db_path_hint:    'Vollständiger Pfad zu fix_db.sh auf dem Server.',
  },
};

export const translations = writable(EN);
export const lang = writable('en');

export const t = derived(translations, $t => (key) => $t[key] || key);

// ── Watch folders ──────────────────────────────────────────────────────────────
export const watchFolders = writable([]);

// ── Filesystem browser ──────────────────────────────────────────────────────
export const fsCurrentPath = writable('');

// ── Albums ───────────────────────────────────────────────────────────────────
export const allAlbums = writable([]);

// ── Ratings & flags ──────────────────────────────────────────────────────────
// Local cache of user-assigned ratings/flags; key = image_id (number)
export const starRatings = writable({});   // { [id]: 0-5 }
export const colorFlags  = writable({});   // { [id]: 'pick'|'delete'|null }

// ── Lightbox refresh ─────────────────────────────────────────────────────────
// Increment to force the lightbox to reload its image (e.g., after rotate)
export const lightboxKey = writable(0);

// ── Gallery refresh tick ──────────────────────────────────────────────────────
// Increment to trigger a gallery reload (e.g., after upload completion)
export const galleryRefreshTick = writable(0);

// ── Background task (e.g., "Add to DB" SSE) ──────────────────────────────────
// { label: string, done: number, total: number } | null
export const backgroundTask = writable(null);

// ── Hybrid ingest mode (when Electron is connected to a remote VPS) ───────────
// 'upload_full'    — Electron uploads full images → VPS processes (default)
// 'local_process'  — Electron runs InsightFace → uploads embeddings only
export const processingMode   = writable('upload_full');
export const localModel       = writable('buffalo_l');
export const localModelStatus = writable({});   // { buffalo_l: bool, ... }

// ── Derived ───────────────────────────────────────────────────────────────────
export const activeFilterCount = derived(filters, $f =>
  Object.values($f).filter(v => v && v.trim()).length
);
