import { writable, derived } from 'svelte/store';

// ── Gallery state ──────────────────────────────────────────────────────────
export const galleryImages  = writable([]);    // current browse results
export const galleryMode    = writable('grid'); // grid | table
export const selectedId     = writable(null);  // lightbox target image id (single click/open)
export const selectedItems  = writable(new Set()); // Set of selected image IDs
export const lastClickedId  = writable(null);  // for shift-click selection
export const galleryLoading = writable(false);
export const backendReady   = writable(false);
export const isOffline      = writable(false);   // true when server unreachable but cached data available
export const syncStatus     = writable(null);    // { syncing, phase, done, total } | null

// ── Filters & sort ──────────────────────────────────────────────────────────
export const filters = writable({
  person:   '',
  tag:      '',
  scene:    '',
  folder:   '',
  path:     '',
  dateFrom: '',
  dateTo:   '',
  creator:  '',
  searchFields: 'filename,path,description', // default fields to include in text search
});
export const sortBy   = writable('newest');  // newest | oldest | date_taken_desc | ...
export const thumbSize = writable(200);       // px; drives CSS var + API size param

// ── Sidebar view ─────────────────────────────────────────────────────────────
// 'all' | 'people' | 'tags' | 'dates' | 'process' | 'train' | 'settings'
export const sidebarView = writable('all');
export const sidebarCollapsed = writable(false);  // icon-only mode for small screens
export const navCollapsed     = writable(true);   // collapsable NAVIGATION section
export const importCollapsed  = writable(true);   // collapsable IMPORT section
export const statsCollapsed   = writable(true);   // collapsable STATS section
export const showLegalModal   = writable(false);  // show legal/imprint modal

// ── Clipboard ───────────────────────────────────────────────────────────────
// { mode: 'copy' | 'move', items: [ { id, path, filename } ] }
export const clipboard = writable(null);

// ── Auth ──────────────────────────────────────────────────────────────────────
export const currentUser = writable(null);   // { username, role } | null

// ── Processing ────────────────────────────────────────────────────────────────
export const processingJobs = writable([]);  // SSE batch jobs

// ── People ────────────────────────────────────────────────────────────────────
export const allPeople    = writable([]);
export const selectedPerson = writable(null);  // person object for detail view

// ── Stats ─────────────────────────────────────────────────────────────────────
export const stats = writable({});

// ── Model warm-up state ───────────────────────────────────────────────────────
export const modelReady = writable(false);

// ── Tags & scenes ─────────────────────────────────────────────────────────────
export const allTags   = writable([]);
export const allScenes = writable([]);

// ── i18n ──────────────────────────────────────────────────────────────────────
// English defaults so the UI is readable before the backend responds
const EN = {
  app_title: 'CrispLens', app_subtitle: 'AI-Powered Image and Face Recognition',
  version: 'Version', welcome: 'Welcome', logout: 'Logout', login: 'Login',
  details: 'Details', training_in_progress: 'Training',
  tab_recognize: 'Recognize', tab_train: 'Train', tab_people: 'People',
  tab_tags: 'Tags', tab_search: 'Search', tab_browse: 'Browse',
  tab_batch: 'Batch Process', tab_stats: 'Statistics', tab_settings: 'Settings',
  tab_admin: 'Admin', tab_benchmark: 'Benchmark', tab_export: 'Export', tab_timeline: 'Timeline', tab_folders: 'Folders',
  tab_creators: 'Creators', more_details: 'More details', fields: 'Fields',
  import_options: 'Import Options',
  upload_image: 'Upload Image', upload_multiple: 'Upload Multiple Images',
  process_image: 'Process Image', processing: 'Processing...', detection_results: 'Detection Results',
  total_faces: 'Total Faces', known_people: 'Known People', unknown_people: 'Unknown People',
  ai_analysis: 'AI Analysis', description: 'Description', filename: 'Filename',
  scene_type: 'Scene Type', tags: 'Tags', confidence: 'Confidence', quality: 'Quality',
  date_created: 'Date Created', date_modified: 'Date Modified', camera_model: 'Camera Model',
  exif_date: 'EXIF Date', date_imported: 'Imported', date_processed: 'Processed',
  stored_thumbnail: 'stored', file_size: 'File size',
  person_name: 'Person Name', training_images: 'Upload Training Images',
  training_method: 'Training Method', train_upload: 'Upload Images', train_folder: 'Scan Folder',
  folder_path: 'Folder Path', scan_folder: 'Scan Folder', train_system: 'Train System',
  training_complete: 'Training Complete!', training_failed: 'Training Failed',
  training_tips: 'Training Tips',
  search_description: 'Search for images containing specific people',
  search_button: 'Search', search_results: 'Search Results for',
  no_results_found: 'No results found', refresh: 'Refresh',
  browse_description: 'Browse all processed images', filter_options: 'Filter Options',
  filter_by_people: 'Filter by People', sort_by: 'Sort By',
  sort_newest: 'Newest first', sort_oldest: 'Oldest first',
  merge: 'Merge', select_all: 'Select All', deselect_all: 'Deselect All',
  batch_description: 'Process entire folders of images', select_folder: 'Select Folder',
  recursive_scan: 'Include Subfolders', process_folder: 'Process Folder',
  batch_progress: 'Progress', batch_complete: 'Batch Processing Complete!',
  processed: 'Processed', failed: 'Failed', skipped: 'Skipped', remaining: 'Remaining',
  stop_processing: 'Stop', resume_processing: 'Resume',
  stats_overview: 'Overview', stats_total_people: 'Total People', stats_total_images: 'Total Images',
  stats_total_faces: 'Total Faces Detected', stats_database: 'Database',
  refresh_stats: 'Refresh',
  settings_title: 'System Configuration', recognition_settings: 'Recognition Settings',
  backend: 'Backend', model: 'Model', detection_threshold: 'Detection Threshold',
  recognition_threshold: 'Recognition Threshold', use_gpu: 'Use GPU',
  ai_enrichment: 'AI Enrichment', enable_vlm: 'Enable VLM',
  vlm_provider: 'VLM Provider', vlm_api_key: 'API Key', vlm_model: 'Model', vlm_max_size: 'Downsizing (Max Dim)',
  ui_settings: 'User Interface', language: 'Language',
  save_settings: 'Save Settings', reset_settings: 'Reset',
  user_management: 'User Management', username: 'Username', password: 'Password',
  role: 'Role', active: 'Active', last_login: 'Last Login', actions: 'Actions',
  unidentified: 'Unidentified',
  role_admin: 'Administrator', role_user: 'User',
  no_image: 'Please upload an image', no_faces_detected: 'No faces detected',
  settings_saved: 'Settings saved', error: 'Error', success: 'Success',
  please_wait: 'Please wait...', loading: 'Loading...', no_key: 'No key set', of: 'of',
  ok: 'OK', cancel: 'Cancel', save: 'Save', delete: 'Delete', edit: 'Edit',
  view: 'View', download: 'Download', upload: 'Upload', clear: 'Clear', reset: 'Reset',
  confirm: 'Confirm', back: 'Back', next: 'Next', previous: 'Previous',
  search_by_date: 'Date',
  change_password: 'Change Password',
  current_password: 'Current Password',
  new_password: 'New Password',
  confirm_password: 'Confirm Password',
  password_changed: 'Password changed successfully',
  set_password: 'Set Password',
  test_key: 'Test',
  key_valid: 'Key valid',
  key_invalid: 'Invalid key',
  // Cloud drives
  cloud_drives: 'Cloud Drives',
  add_drive: 'Add Drive',
  no_cloud_drives: 'No cloud drives configured',
  no_cloud_drives_hint: 'Add a network share or cloud storage account',
  drive_name: 'Drive Name', drive_type: 'Type', drive_host: 'Host', drive_server: 'Server',
  drive_share: 'Share', drive_username: 'Username', drive_password: 'Password',
  drive_domain: 'Domain', drive_port: 'Port', drive_remote_path: 'Remote Path',
  drive_ssh_key: 'SSH Key', drive_email: 'Email', drive_tfa: '2FA Code',
  drive_mount_point: 'Mount Point', drive_read_only: 'Read Only',
  drive_scope: 'Scope', drive_scope_system: 'System', drive_scope_user: 'Personal',
  drive_allowed_roles: 'Allowed Roles', drive_auto_mount: 'Auto-mount',
  drive_edit: 'Edit', drive_save: 'Save Drive', drive_delete: 'Delete Drive',
  drive_delete_confirm: 'Delete this drive?',
  drive_connect: 'Connect', drive_disconnect: 'Disconnect',
  drive_mount: 'Mount', drive_unmount: 'Unmount', drive_test: 'Test',
  drive_status_connected: 'Connected', drive_status_mounted: 'Mounted', drive_status_offline: 'Offline',
  drive_placeholder_name: 'My Drive', drive_placeholder_host: 'e.g. 192.168.1.1',
  drive_placeholder_server: '//server/share', drive_placeholder_share: 'share',
  drive_placeholder_remote_path: '/remote/path', drive_placeholder_ssh_key: '/path/to/key',
  drive_placeholder_tfa: '2FA code', drive_placeholder_mount_smb: '/mnt/smb',
  drive_placeholder_mount_sftp: '/mnt/sftp',
  // Face identification / clusters
  face_identification: 'Face Identification', face_clusters: 'Face Clusters',
  face_num: 'Face #', identify_persons: 'Identify',
  person_name_placeholder: 'Enter name…', type_name_placeholder: 'Type a name…',
  enter_person_name: 'Enter person name',
  all_faces_identified: 'All faces identified', no_faces_in_image: 'No faces in this image',
  no_clusters_found: 'No face clusters found', no_clusters_detail: 'Process more images to generate face clusters',
  clustering_faces: 'Clustering faces…', similarity_threshold: 'Similarity threshold',
  lower_threshold_hint: 'Lower threshold = more results',
  recognition_certainty: 'Certainty', conf_short: 'Conf',
  clear_all_identifications: 'Clear all identifications',
  clear_all_detections: 'Clear all detections',
  drag_to_mark_face: 'Drag to mark a face',
  // Train
  browse_button: 'Browse', train_folder_description: 'Scan folder for named sub-folders (one per person)',
  // Sort options
  sort_date_taken_asc: 'Date taken (oldest)', sort_date_taken_desc: 'Date taken (newest)',
  sort_filename_az: 'Filename A–Z', sort_most_faces: 'Most faces',
  // Stats
  stats_images_with_date: 'Images with date',
  // Lightbox / image ops
  zoom_in: 'Zoom in', zoom_out: 'Zoom out', fit_to_screen: 'Fit to screen',
  press_esc_to_close: 'Press Esc to close', close: 'Close',
  run_detection: 'Run detection', remove_detection: 'Remove detection',
  run_vlm_only: 'Run VLM only',
  min_face_size: 'Min Face Size',
  downsize_before_detect: 'Downsize before detect (px)',
  downsize_before_vlm: 'Downsize before VLM (px)',
  // Detection model labels
  det_model_auto: 'Auto (default)',
  det_model_retinaface: 'RetinaFace',
  det_model_scrfd: 'SCRFD',
  det_model_yunet: 'YuNet',
  det_model_mediapipe: 'MediaPipe',
  det_model_none: 'None (VLM only)',
  vlm_prompt: 'Analyze this image and provide: 1. A short description. 2. A scene type (e.g. portrait, landscape, etc). 3. A list of keyword tags.',
  // API server + processing backend (v4)
  api_server_section:         'API / Database Server',
  api_server_url_label:       'Server URL',
  api_server_hint:            'URL we send all API calls to (images, people, faces, DB). Point this to any CrispLens server — local v4 Node.js, remote v2 FastAPI, or another host. Inference runs on whichever server handles the API.',
  api_server_connect:         'Connect',
  api_server_saved:           'Saved servers',
  api_server_save_as:         'Save as',
  api_server_preset_ph:       'Preset name…',
  api_server_save_preset:     'Save',
  processing_backend_section: 'Inference Engine (Axis 3)',
  processing_backend_hint:    'Where does face detection and embedding run? Local = v4 Node.js ONNX on this machine. Remote v2 = Python/InsightFace on a separate server. Remote v4 = ONNX on a separate v4 Node.js server.',
  backend_local:              'Local (Node.js ONNX)',
  backend_remote_v2:          'Remote v2 Python FastAPI',
  backend_remote_v4:          'Remote v4 Node.js API',
  remote_v2_url:              'Remote Server URL',
  remote_v2_user:             'Username',
  remote_v2_pass:             'Password',
  remote_v2_mode:             'Inference mode',
  remote_v2_upload_bytes:     'Upload image → remote inference',
  remote_v2_local_infer:      'Local inference → send vectors only',
  remote_v2_test:             'Test Connection',
  remote_v2_connected:        'Connected',
  remote_v2_unreachable:      'Unreachable',
  pipeline_local:             'Local',
  pipeline_remote_v2:         'Remote v2',
  pipeline_remote_v4:         'Remote v4',
  // ONNX backend settings (browser)
  ort_browser_section:        'Inference Providers',
  ort_browser_hint:           'Controls which GPU/WASM backends onnxruntime-web uses. Changes take effect after reloading.',
  ort_use_simd:               'SIMD acceleration',
  ort_use_simd_hint:          'Faster WASM (~2-4×). Experimental — disable if the engine crashes.',
  ort_use_webgl:              'WebGL acceleration',
  ort_use_webgl_hint:         'Uses GPU for model inference. Disable if you see crashes.',
  ort_use_webgpu:             'WebGPU (experimental)',
  ort_use_webgpu_hint:        'Next-gen GPU — Chrome 113+ / Edge only. Falls back to WebGL/WASM if unsupported.',
  // ONNX backend settings (server)
  ort_server_section:         'Server ONNX Providers',
  ort_server_hint:            'Hardware acceleration for the Node.js face engine. Requires restart after change.',
  ort_use_coreml:             'CoreML (Apple Silicon / macOS)',
  ort_use_coreml_hint:        '~5-10× faster on Mac with Apple Silicon. No extra install needed.',
  ort_use_cuda:               'CUDA (NVIDIA GPU)',
  ort_use_cuda_hint:          'Requires CUDA toolkit + onnxruntime-node GPU build.',
  ort_use_directml:           'DirectML (Windows GPU)',
  ort_use_directml_hint:      'Hardware acceleration on Windows for AMD/NVIDIA/Intel GPUs.',
  ort_recommended:            'Recommended for this platform',
  ort_no_accel_available:     'No platform-specific acceleration available (WASM CPU only).',
  // Detector status messages (engine status panel)
  settings_detectors:         'Detectors',
  det_model_not_downloaded:   'model not yet downloaded',
  det_lib_missing:            'library missing',
  det_not_loaded:             'not loaded',
  det_model_corrupt:          'model corrupt',
  // Generate / BFL
  gen_seed_random: 'random',
  // Misc
  apply: 'Apply', apply_to_all: 'Apply to all', apply_to_selected: 'Apply to selected',
  skip: 'Skip', rescan: 'Rescan', scanning: 'Scanning…', save_all: 'Save all',
  deselect: 'Deselect', selection: 'Selection', source: 'Source', target: 'Target',
  search_name: 'Search by name…', operation_cancelled: 'Cancelled',
  people_detected: 'People detected', process_more_images: 'Process more images',
  image_pending: '1 image pending', images_pending: '{n} images pending',
  // Events
  photo: 'photo', photos: 'photos', event_singular: 'event',
  events: 'Events', time_gap: 'Time gap:', grouping_by_time: 'Grouping by time…',
  no_events_found: 'No events found. Images may lack date metadata.',
  event_name_placeholder: 'Add event name…', open_event: 'Open event →',
  // Identify
  all_faces: 'All faces', no_images_with_faces: 'No images with detected faces.',
  // Watch Folders
  watch_folders: 'Watch Folders', wf_path_placeholder: 'Folder path…',
  add: 'Add', no_watch_folders: 'No watch folders yet.',
  no_watch_folders_sub: 'Add a folder above to automatically ingest new images.',
  recursive: 'Recursive', auto_scan_label: 'Auto-scan', every: 'Every',
  files_added_stat: 'added', last_scan_time: 'Last scan time',
  scan_complete_msg: 'Scan complete', scan_now: 'Scan Now', auto_scan_every: 'Auto-scan every',
  wf_already_watched: 'This folder is already being watched.',
  new_label: 'new', found_label: 'found', errors_label: 'errors',
  dismiss: 'Dismiss', images_added_count: 'images added.',
  // Duplicates
  duplicates: 'Duplicates', dup_method: 'Method',
  dup_method_name_size: 'Filename + Size', dup_method_hash: 'Binary hash (SHA256)',
  dup_method_visual: 'Visual (pHash)', dup_threshold: 'Threshold',
  dup_keep: 'Keep', dup_keep_most_faces: 'Most faces',
  dup_keep_oldest: 'Oldest file', dup_keep_largest: 'Largest file',
  dup_action: 'Action', dup_delete_from_disk: 'Delete from disk',
  dup_remove_db_only: 'Remove from DB only', dup_replace_symlink: 'Replace with symlink',
  dup_merge_faces: 'Merge face assignments', dup_resolve_selected: 'Resolve selected',
  dup_resolving: 'Resolving…', dup_resolved: '✓ Resolved', dup_resolve: 'Resolve',
  dup_role_guard: 'Resolving duplicates requires mediamanager or admin access',
  dup_view_only: 'View only', no_duplicates: 'No duplicates found with this method.',
  dup_run_scan_first: 'Run "Scan pHash" above first.',
  dup_copies: 'copies', dup_groups: 'groups', dup_keep_chip: '✓ Keep', dup_del_chip: 'Delete',
  computing_hashes: 'Computing hashes…',
  hash_scan_complete: 'Hash scan complete — duplicates updated',
  fill_hashes: 'Fill Hashes', scanning_phash: 'Scanning pHash…',
  scan_phash_btn: 'Scan pHash', phash_scan_complete: 'pHash scan complete',
  all_images_have_phash: 'All images have pHash',
  imagehash_not_installed: 'imagehash not installed on the server.',
  recoverable: 'recoverable',
  cleanup_source_files: 'Clean up source files',
  cleanup_originals_hint: 'These originals live outside the server copy — the server-side file was already handled. Choose what to do with the originals on their source machine:',
  cleanup_action: 'Action', cleanup_trash_opt: 'Move to Trash (reversible)',
  cleanup_delete_opt: 'Delete permanently',
  cleanup_symlink_opt: 'Replace with symlink to kept file',
  download_script: 'Download script', review_before_run: 'Review before running',
  delete_via_browser: 'Delete via browser',
  browser_local_only: 'Grants per-folder permission — local files only',
  move_to_trash: 'Move to Trash',
  sends_to_os_trash: 'Sends files to your OS Trash (reversible)',
  download_json_list: 'Download JSON list',
  import_to_local: 'Import into your local Electron client to trash files there',
  import_cleanup_json: 'Import cleanup JSON',
  execute_downloaded_json: 'Execute a previously downloaded cleanup JSON on this machine',
  by_name_size: 'By name+size:', by_hash: 'By hash:', stat_visual: 'Visual:',
  wasted: 'Wasted:', origin_label: 'origin:',
  // Filesystem
  fs_server_mode: 'Server', fs_local_mode: 'Local', fs_cloud_mode: 'Cloud',
  select_drive_below: 'Select a drive below',
  fs_in_db: 'In DB', fs_not_in_db: 'Not in DB', fs_no_images: 'no images',
  fs_folder_label: 'folder', fs_image_label: 'image', fs_file_label: 'file',
  fs_empty_folder: 'This folder is empty.',
  fs_name_col: 'Name', fs_status_col: 'Status', fs_size_col: 'Size',
  fs_fetching: 'Fetching', fs_uploading: 'Uploading', fs_adding: 'Adding',
  fs_images_only: '(images only)', fs_images_folders: '(images + folders)',
  fs_already_in_db: 'already in DB.', fs_go: 'Go', fs_path_placeholder: 'Enter path…',
  fs_select_cloud_drive: 'Select a cloud or network drive to browse:',
  fs_no_cloud_drives_fs: 'No cloud drives configured.',
  fs_add_in_settings: 'Add drives in Settings → Cloud Drives.',
  fs_grant_access: 'Grant access to folder…',
  fs_pick_local_folder: 'Pick a local folder — will ask for permission to read it.',
  fs_select_images: 'Select images…', fs_select_folder_btn: 'Select folder…',
  fs_rename: 'Rename', fs_trash: 'Trash', fs_loading_drives: 'Loading drives…',
  fs_not_connected: 'Not connected — connect in Cloud Drives first',
  fs_add_to_db: 'Add to DB', fs_add_to_db_cloud: 'Add to DB from cloud',
  fs_upload_to_db: 'Upload to DB', fs_shared: 'Shared', fs_private: 'Private',
  fs_select_drive_to_add: 'select images or folders to add to DB',
  fs_upload_to_server: 'select images to upload to server DB',
  fs_change_folder: 'Change folder…',
  fs_local_folder_hint: 'Local folder — click "Grant access" to browse your device',
  fs_local_upload_hint: 'Local upload — pick images or a folder from your device',
  // Context menu
  ctx_open_external: 'Open file', ctx_open_folder: 'Open folder',
  ctx_browse_folder: 'Browse folder', ctx_add_to_album: 'Add to Album',
  ctx_no_albums: 'No albums — create one first', ctx_new_album: '+ New album…',
  ctx_people_in_image: 'People in this image', ctx_all_photos_of: 'All photos of',
  ctx_crop_image: 'Crop image', ctx_adjust_image: 'Adjust image',
  ctx_convert_export: 'Convert / Export', ctx_download_file: 'Download file',
  ctx_copy_path: 'Copy file path',
  // Convert modal
  conv_format: 'Format', conv_quality: 'Quality', conv_resize: 'Resize',
  conv_no_resize: 'No resize', conv_fit: 'Fit within (keep ratio)',
  conv_exact: 'Exact dimensions', conv_max_size: 'Max size', conv_save_as: 'Save as',
  conv_replace_orig: 'Replace original', conv_new_file: 'New file',
  conv_output_folder: 'Output folder', conv_suffix: 'Suffix', conv_folder: 'Folder',
  conv_done: 'Done', conv_converting: 'Converting…', conv_convert: 'Convert',
  // Adjust modal
  adj_input_levels: 'Input Levels', adj_output: 'Output', adj_presets: 'Presets',
  adj_light: 'Light', adj_brightness: 'Brightness', adj_contrast: 'Contrast',
  adj_colour: 'Colour', adj_saturation: 'Saturation', adj_warmth: 'Warmth',
  adj_detail: 'Detail', adj_sharpness: 'Sharpness', adj_save_as: 'Save as',
  adj_replace_orig: 'Replace original', adj_new_file: 'New file', adj_suffix: 'Suffix',
  adj_applying: 'Applying…', adj_reset_all: 'Reset All', adj_saved: '✓ Saved',
  selected_label: 'selected',
  // BFL AI editing
  bfl_outpaint: 'Outpaint', bfl_inpaint: 'Inpaint', bfl_ai_edit: 'AI Edit',
  bfl_add_top: 'Add Top', bfl_add_bottom: 'Add Bottom',
  bfl_add_left: 'Add Left', bfl_add_right: 'Add Right',
  bfl_mask_x: 'Mask X', bfl_mask_y: 'Mask Y',
  bfl_mask_w: 'Mask W', bfl_mask_h: 'Mask H',
  bfl_prompt_optional: 'Prompt (optional)',
  bfl_edit_prompt: 'Describe the edit…',
  bfl_inpaint_prompt: 'What to generate in the masked area…',
  bfl_model: 'Model',
  bfl_applying: 'Generating…', bfl_done: '✓ Generated',
  bfl_no_key: 'BFL API key not configured — add it in Settings → API Keys',
  ctx_ai_edit: 'AI Edit (BFL)',
  conv_resize_outpaint: 'Outpaint (AI)',
  bfl_generate: 'Generate',
  bfl_gen_prompt: 'Describe what to generate…',
  bfl_aspect_ratio: 'Aspect ratio',
  bfl_output_folder: 'Output folder',
  bfl_filename_prefix: 'Filename prefix',
  bfl_gen_hint: 'Thumbnail shown for reference — not sent to the model',
  bfl_gen_hint_include: 'Thumbnail shown for reference — will be sent as input image',
  bfl_include_ref_image: 'Include as reference image (input_image)',
  bfl_width: 'Width (px)',
  bfl_height: 'Height (px)',
  bfl_steps: 'Steps',
  bfl_guidance: 'Guidance',
  bfl_seed: 'Seed',
  bfl_zoom: 'Zoom',
  bfl_drag_hint: 'Drag edges to set border size',
  bfl_mask_hint: 'Drag to position the fill area',
  // Sidebar nav labels
  tab_albums: 'Albums',
  tab_events: 'Events',
  tab_identify: 'Identify',
  tab_faceclusters: 'Face Clusters',
  tab_filesystem: 'Filesystem',
  tab_watchfolders: 'Watch Folders',
  tab_duplicates: 'Duplicates',
  tab_ingest: 'Ingest',
  sidebar_expand: 'Expand sidebar',
  sidebar_collapse: 'Collapse sidebar',
  tab_about: 'About CrispLens',
  tab_privacy: 'Privacy',
  legal_imprint: 'Imprint / Legal',
  // Crop / Canvas Size modal
  tab_generate: 'Generate',
  crop_image: 'Crop Image',
  canvas_size: 'Canvas Size',
  crop_aspect_ratio: 'Aspect ratio',
  crop_selection_px: 'Selection (px)',
  crop_reset: '↺ Reset',
  crop_filename_hint: 'Filename (auto if blank)',
  crop_and_save: 'Crop & Save',
  saving: 'Saving…',
  save_as: 'Save as',
  save_as_replace: 'Replace original',
  save_as_new_file: 'New file',
  canvas_add_border: 'Add border (px)',
  canvas_fill_mode: 'Fill mode',
  canvas_fill_solid: 'Solid color',
  canvas_fill_mirror: 'Mirror edge',
  canvas_fill_outpaint: 'AI Outpaint',
  canvas_fill_outpaint_hint: 'Will open AI Edit → Outpaint tab',
  canvas_apply: 'Apply Canvas Size',
  // Generate view
  gen_image_title: 'Generate Image',
  gen_model_label: 'Model',
  gen_prompt_label: 'Prompt',
  gen_prompt_placeholder: 'Describe what to generate…',
  gen_filename_prefix: 'Filename prefix',
  gen_output_folder: 'Output folder (optional)',
  gen_output_folder_hint: 'Leave blank to use default generated/ folder',
  gen_result_title: 'Generated Image',
  gen_view_in_gallery: 'View in gallery',
  gen_generating: 'Generating…',
  // Done-panel actions (shared between AIEditModal and GenerateView)
  done_without_db: 'Without DB',
  done_view_raw: 'View (no DB)',
  done_download_raw: 'Download (no DB)',
  done_save_to_db: 'Save to DB',
  done_save_only: 'Save only',
  done_save_gallery_title: 'Register in DB and open in gallery',
  done_save_lightbox_title: 'Register in DB and open image',
  done_save_silent_title: 'Register in DB and close',
  done_generate_another: 'Generate another',
  // Detection model selector (shared)
  rescan_mode_both: 'Both', rescan_mode_faces: 'Faces', rescan_mode_vlm: 'VLM',
  also_run_vlm: 'Also refresh VLM',
  // Settings — section titles + labels
  settings_server_section:    'Node.js Server',
  settings_mode_run_local:    'Run locally on this machine',
  settings_mode_run_local_hint:'App manages its own Node.js/Express server (Python-free)',
  settings_mode_remote:       'Connect to remote server (VPS)',
  settings_mode_remote_hint:  'Point to an existing CrispLens v4 Node.js or v2 FastAPI instance',
  settings_server_restart_hint:'Changes to server mode require a restart.',
  settings_restart_wasm:      'Restart WASM Engine',
  settings_local_port:        'Local port',
  settings_server_url:        'Server URL',
  settings_db_section:        'Database',
  settings_db_switch_hint:    'Switch between local SQLite database files (photo collections). Requires restart.',
  settings_db_current:        'Current DB',
  settings_db_switch_to:      'Switch to',
  settings_db_switch_btn:     'Switch Database & Restart',
  settings_db_remote_info:    'Database is managed by the remote server.',
  settings_img_proc_section:  'Image Processing',
  settings_python_path:       'Python path',
  settings_upload_mode:       'Upload images to server',
  settings_upload_mode_hint:  'Send local images to VPS — server runs InsightFace + VLM',
  settings_local_proc_mode:   'Process locally, upload results',
  settings_local_proc_mode_hint:'Run InsightFace here → upload embeddings + thumbnail only (no VLM)',
  settings_local_model:       'Local model',
  settings_det_size:          'Detection size',
  settings_det_size_hint:     'Larger values find smaller faces but are slower.',
  settings_storage_section:   'Storage',
  settings_storage_hint:      'Limit the size of images saved on the server after upload. Useful to save disk space when originals are kept on your local machine.',
  settings_upload_max_dim:    'Max upload dimension (px)',
  settings_no_resize:         'Full resolution kept (no resize)',
  settings_resize_hint:       'Images resized before saving',
  settings_db_health:         'Database Health',
  db_path_label:              'Path',
  db_size_label:              'Size',
  db_writable_label:          'Writable',
  db_users_label:             'Users',
  db_images_label:            'Images',
  hard_reset_app:             'Reset Settings (Safe)',
  reload_after_settings:      'Reload the page after changing these settings.',
  settings_engine_section:    'Face Recognition Engine',
  settings_engine_ready:      '✓ Ready',
  settings_engine_not_ready:  '✗ Not ready',
  settings_reload_engine:     'Reload Engine',
  detection_model:            'Detection Model',
  det_model_global_hint:      'Global default',
  add_user:                   'Add User',
  settings_db_backup_title:   'Standalone Backup & Portability',
  settings_db_backup_hint:    'Use these to move your data between local or devices.',
  settings_db_export:         'Export Database',
  settings_db_import:         'Import Database',
  settings_db_clear:          'Clear Everything',
  settings_db_clear_confirm:  'This will delete all images, people, and settings from your local database. CANNOT BE UNDONE. Continue?',
  settings_db_import_confirm: 'Importing will overwrite/merge with existing data. Continue?',
  // Admin — server management
  admin_server_mgmt:   'Server Management',
  admin_update_server: 'Update Server',
  admin_view_logs:     'View Logs',
  admin_run_update:    'Run Update',
  update_modal_hint:   'This will run fix_db.sh as root (git pull + DB migrations + service restart). The connection will drop when the server restarts.',
  root_password:       'Root password',
  running:             'Running…',
  admin_logs_title:    'Server Logs',
  logs_refresh:        'Refresh',
  logs_follow:         'Follow',
  logs_path:           'Log file',
  // Admin — copy-exempt paths
  exempt_paths_label:  'Copy-exempt server paths',
  exempt_paths_hint:   'Files uploaded from these server paths are recorded in-place (no copy to uploads/).',
  fix_db_path_label:   'fix_db.sh path',
  fix_db_path_hint:    'Full path to fix_db.sh on the server.',
  // ProcessView — mode badges, controls, drop zone, server folder, detection settings
  pv_mode_local:             'Local process',
  pv_mode_upload:            'Upload full',
  pv_mode_web_infer:         'Web inference',
  pv_web_local_infer:        'Local inference',
  pv_web_local_infer_hint:   'Detect & embed faces locally using ONNX — only vectors sent to server. First run downloads models (~180 MB, cached after).',
  pv_clear_done:             'Clear done',
  pv_clear_all:              'Clear all',
  pv_local_base_label:       'Local base folder (optional):',
  pv_local_base_placeholder: '/Users/you/Downloads/pics',
  pv_local_base_hint:        'Prepended to filenames when device cannot expose the full path',
  pv_local_path_notice:      'Local base folder required for persistent jobs',
  pv_drop_active:            'Drop to add to queue',
  pv_drop_idle:              'Drop images or folders here',
  pv_drop_sub:               'Multiple files supported · JPEG, PNG, WebP, …',
  pv_select_files:           'Select files…',
  pv_select_folder_btn:      'Select folder…',
  pv_item:                   'item',
  pv_items:                  'items',
  pv_pending:                'pending',
  pv_process_btn:            '▶ Process',
  pv_process_direct:         'Direct',
  pv_process_direct_hint:    'Process files now in the queue (not persistent)',
  pv_process_as_batch:       'As Batch',
  pv_uploading_progress:     'Uploading {n} / {total}…',
  pv_image:                  'image',
  pv_images:                 'images',
  pv_server_folder_label:    'Or process a server-side folder directly',
  pv_server_folder_ph:       '/data/photos  (path on the VPS)',
  pv_browse:                 'Browse…',
  pv_subfolders:             'Subfolders',
  pv_det_settings:           'Detection Settings',
  pv_skip_faces:             'Skip face recognition',
  pv_skip_vlm:               'Skip AI description (VLM)',
  pv_max_size_label:         'Resize to (px)',
  pv_max_size_hint:          '0 = Original',
  pv_already_uploaded:       'already uploaded',
  pv_shared_by_others:       'shared by others',
  pv_badge_pending:          'pending',
  pv_badge_processing:       'processing…',
  pv_badge_error:            'error',
  pv_own_dup_title:          'Already uploaded by you',
  pv_shared_dup_title:       'Same content already uploaded by another user',
  pv_remove:                 'Remove',
  pv_vlm_desc_received:      'VLM description received',
  pv_vlm_tags_received:      'VLM tags received',
  pv_faces_identified:       'Faces identified',
  pv_matched_in_index:       'Matched in index',
  pv_dup_mode_label:         'Duplicates',
  pv_dup_mode_skip:          'Skip (don\'t re-process)',
  pv_dup_mode_overwrite:     'Overwrite (re-process, keep same row)',
  pv_dup_mode_add:           'Always add (ignore duplicates)',
  pv_dup_skipped:            'skipped (duplicate)',

  // Standalone / Storage mode
  settings_storage_mode:     'Data Source (Axis 1)',
  settings_storage_mode_hint: 'Where does image/people data come from? Server connects to a v4 Node.js or v2 FastAPI backend (Axis 2 sets which one). Standalone uses on-device SQLite — no server required, ideal for iOS/Android offline use.',
  settings_standalone_active: '⚡ Standalone mode active. Face detection and recognition run on-device using ONNX models cached below. Cloud VLM enrichment (optional) calls external API providers directly — no server needed.',
  settings_sync_target:      'Sync Target',
  settings_sync_target_hint: 'Set the remote server to push/pull data from when in standalone mode.',
  settings_det_retries:      'Detection Retries',
  settings_det_retries_hint: 'Fallback attempts with lower threshold if 0 faces found',
  settings_model_cached:     'cached',
  settings_model_not_found:  'not downloaded',
  settings_models_download_hint: 'Models are downloaded from the connected server and cached on-device (~185 MB total). Download once while online, then use offline forever.',
  settings_db_diag:          'Database Diagnostics',
  settings_engine_status:    'Face Recognition Engine',
  settings_engine_backend:   'Backend',
  settings_engine_model:     'Model',
  settings_transport_diag:   'SSE / transport diagnostics',

  // Tag + album pickers in ProcessView
  pv_tags_label:             'Tags',
  pv_tags_placeholder:       'Pick or type new tag…',
  pv_album_label:            'Album',
  pv_album_placeholder:      'Pick or type new album…',
  pv_album_new_prefix:       'Create:',
  pv_creator_label:          'Creator',
  pv_creator_placeholder:    'Creator name…',
  pv_copyright_label:        'Copyright',
  pv_copyright_placeholder:  '© 2025 Name…',
  pv_submit_batch_job:       'Create batch job',
  pv_follow_symlinks:        'Follow symbolic links',

  // Archive metadata fields (MetaPanel)
  archive_metadata:            'Archiv-Metadaten',
  arch_fachbereich:            'Fachbereich',
  arch_veranstaltungsnummer:   'Veranstaltungsnummer',
  arch_datum:                  'Datum',
  arch_veranstaltungstitel:    'Veranstaltungstitel',
  arch_urheber:                'Urheber',

  // Batch Jobs view
  tab_batchjobs:             'Batch Jobs',
  bj_title:                  'Batch Jobs',
  bj_no_jobs:                'No batch jobs yet.',
  bj_no_jobs_hint:           'Create one in Process → server folder section.',
  bj_status_pending:         'Pending',
  bj_status_running:         'Running',
  bj_status_paused:          'Paused',
  bj_status_cancelled:       'Cancelled',
  bj_status_done:            'Done',
  bj_status_error:           'Error',
  bj_start:                  'Start',
  bj_resume:                 'Resume',
  bj_cancel:                 'Cancel',
  bj_delete:                 'Delete',
  bj_view_logs:              'View logs',
  bj_logs_title:             'Error log',
  bj_logs_empty:             'No errors.',
  bj_logs_save:              'Download log',
  bj_source:                 'Source',
  bj_created:                'Created',
  bj_total:                  'Total',
  bj_done:                   'Done',
  bj_errors:                 'Errors',
  bj_delete_confirm:         'Delete this job and its file log?',
  bj_cancel_confirm:         'Cancel this running job?',
  bj_file_inaccessible:      'File not accessible',
  bj_enum_started:           'Enumerating files…',
  bj_show_all_users:         'Show all users (admin)',
  bj_tags_applied:           'Tags',
  bj_album_applied:          'Album',
  bj_progress:               'Progress',
  bj_name:                   'Name',
  bj_retry:                  'Retry failed',
  bj_persistent_hint:        'Create a persistent server-side job for these files',
  bj_source_selection:       'Manual selection',

  // Offline / local cache (browser/PWA sync)
  offline_cache_section:     'Offline Cache',
  offline_cache_hint:        'Download the most recent images and thumbnails for offline browsing. The service worker caches thumbnails automatically as you browse; use Sync to prefetch a larger set.',
  offline_max_images:        'Max images to cache',
  offline_max_size_mb:       'Max cache size (MB)',
  offline_sync_btn:          'Sync now',
  offline_syncing:           'Syncing…',
  offline_clear:             'Clear cache',
  offline_stats_images:      'images cached',
  offline_stats_size:        'MB used',
  offline_last_sync:         'Last sync:',
  offline_never_synced:      'Not yet synced',
  offline_phase_metadata:    'Fetching metadata…',
  offline_phase_thumbnails:  'Caching thumbnails',
  offline_phase_done:        'Sync complete',
  offline_cleared:           'Cache cleared',
  offline_banner:            '⚡ Offline — showing cached data',
  offline_thumb_size:        'Thumbnail size',
  offline_thumb_size_hint:   "Controls the resolution of thumbnails downloaded for offline use AND the resolution of images stored in your browser's Standalone database.",
  offline_pending_push:      'item(s) queued to push',
  offline_push_btn:          'Push now',
  offline_push_hint:         'Upload locally-processed images to the server',
  offline_pushing:           'Pushing…',
  pv_queued_offline:         'Queued — will sync when online',
  pv_local_pick_title:       'Pick photos from your library',
  pv_local_pick_sub:         'Faces are recognised on-device — no server required',
  pv_local_pick_btn:         'Select Photos',
  // Archive / Bildarchiv
  archive_meta_title: 'Archiv-Metadaten',
  archive_fachbereich: 'Fachbereich',
  archive_veranstaltungsnummer: 'Veranstaltungsnummer',
  archive_datum: 'Datum',
  archive_veranstaltungstitel: 'Veranstaltungstitel',
  archive_urheber: 'Urheber',
  archive_action: 'Dateiaktion',
  archive_action_leave: 'Belassen (nur Metadaten)',
  archive_action_copy: 'Kopieren nach Archiv',
  archive_action_move: 'Verschieben nach Archiv',
  archive_write_exif: 'EXIF/XMP-Metadaten schreiben',
  archive_bildauswahl: 'Als Unterauswahl ablegen',
  archive_bildauswahl_copy: 'Kopieren',
  archive_bildauswahl_move: 'Verschieben',
  archive_rename_resort: 'Umbenennen/Neu sortieren',
  archive_rename_file: 'Datei umbenennen',
  archive_organizing: 'Ordne Dateien…',
  archive_done: 'erledigt',
  archive_errors: 'Fehler',
  archive_path_preview: 'Vorschau Pfad',
  archive_config_title: 'Archiv-Konfiguration',
  archive_config_fields: 'Felder',
  archive_config_bildarchiv: 'Bildarchiv',
  archive_config_bildauswahl: 'Bildauswahl',
  archive_config_base_path: 'Basispfad',
  archive_config_folder_tpl: 'Ordner-Vorlage',
  archive_config_filename_tpl: 'Dateiname-Vorlage',
  archive_config_default_action: 'Standard-Aktion',
  archive_config_create_jpg: 'JPG erstellen falls kein JPEG',
  archive_config_exif_mapping: 'EXIF-Feld-Zuordnung',
  archive_config_save: 'Konfiguration speichern',
  archive_config_saved: '✓ Konfiguration gespeichert',
  archive_field_label: 'Bezeichnung',
  archive_field_type: 'Typ',
  archive_field_choices: 'Auswahloptionen',
  archive_field_allow_custom: 'Freitext erlaubt',
  archive_field_required: 'Pflichtfeld',
  archive_field_add: '+ Feld hinzufügen',
  archive_field_remove: 'Feld entfernen',
  archive_exiftool_available: 'ExifTool verfügbar',
  archive_exiftool_missing: 'ExifTool nicht installiert (EXIF-Schreiben deaktiviert)',
  archive_migrate_files: 'Bestehende Dateien umziehen',
  archive_migrate_confirm: 'Alle archivierten Dateien entsprechend neuer Vorlage umbenennen?',
  archive_tpl_vars_hint: 'Verfügbare Variablen: {fachbereich} {veranstaltungsnummer} {veranstaltungstitel} {urheber} {datum} {year} {month} {description} {names} {counter}',
  // Axis / Settings strings
  axis_title: 'Connection & Inference',
  axis_subtitle: 'Three independent settings control how CrispLens operates.',
  axis_1_label: 'Data Source (Axis 1)',
  axis_1_hint: 'Where does image/people data come from? Server connects to a v4 Node.js or v2 FastAPI backend (Axis 2 sets which one). Standalone uses on-device SQLite — no server required.',
  axis_1_isolation: 'Data Isolation: Server and Standalone modes use separate databases. The local .db file is only used in Server mode. In Standalone mode, data is stored exclusively in your browser\'s IndexedDB (WASM).',
  axis_1_server: 'Server',
  axis_1_server_desc: 'v4 Node.js or v2 FastAPI',
  axis_1_standalone: 'Standalone (Local)',
  axis_1_standalone_desc: 'On-device SQLite (WASM), no server required',
  axis_2_label: 'API / Database Server',
  axis_2_hint: 'URL we send all API calls to (images, people, faces, DB). Point this to any CrispLens server — local v4 Node.js, remote v2 FastAPI, or another host. Inference runs on whichever server handles the API.',
  axis_3_label: 'Inference Engine (Axis 3)',
  axis_3_current: 'Current:',
  bench_title: 'Benchmark',
  bench_hint: 'Test performance of different inference backends on this device.',
  bench_run: 'Run Browser Benchmark',
  api_keys_section: 'API Keys',
  api_keys_regular_user: 'As a regular user you have access to EU-hosted providers only.',
  ai_enrichment_override: 'Personal override — global default:',
};



export const TRANSLATIONS = {
  en: EN,
  de: {
    app_title: 'CrispLens', app_subtitle: 'KI-gestützte Bild- und Gesichtserkennung',
    version: 'Version', welcome: 'Willkommen', logout: 'Abmelden', login: 'Anmelden',
    details: 'Details', training_in_progress: 'Training',
    tab_recognize: 'Erkennen', tab_train: 'Trainieren', tab_people: 'Personen',
    tab_tags: 'Tags', tab_search: 'Suchen', tab_browse: 'Durchsuchen',
    tab_batch: 'Stapelverarbeitung', tab_stats: 'Statistiken', tab_settings: 'Einstellungen',
    tab_admin: 'Admin', tab_benchmark: 'Benchmark', tab_export: 'Export', tab_timeline: 'Zeitleiste', tab_folders: 'Ordner',
    tab_creators: 'Urheber', more_details: 'Mehr Details', fields: 'FELDER',
    import_options: 'Importoptionen',
    upload_image: 'Bild hochladen', upload_multiple: 'Mehrere Bilder hochladen',
    process_image: 'Bild verarbeiten', processing: 'Verarbeitung...', detection_results: 'Erkennungsergebnisse',
    total_faces: 'Gesichter gesamt', known_people: 'Bekannte Personen', unknown_people: 'Unbekannte Personen',
    ai_analysis: 'KI-Analyse', description: 'Beschreibung', filename: 'Dateiname',
    scene_type: 'Szenentyp', tags: 'Schlagworte', confidence: 'Konfidenz', quality: 'Qualität',
    date_created: 'Erstellungsdatum', date_modified: 'Änderungsdatum', camera_model: 'Kameramodell',
    exif_date: 'EXIF-Datum', date_imported: 'Importiert', date_processed: 'Verarbeitet',
    stored_thumbnail: 'gespeichert', file_size: 'Dateigröße',
    person_name: 'Personenname', training_images: 'Trainingsbilder hochladen',
    training_method: 'Trainingsmethode', train_upload: 'Bilder hochladen', train_folder: 'Ordner scannen',
    folder_path: 'Ordnerpfad', scan_folder: 'Ordner scannen', train_system: 'System trainieren',
    training_complete: 'Training abgeschlossen!', training_failed: 'Training fehlgeschlagen',
    training_tips: 'Trainingshinweise',
    search_description: 'Bilder mit bestimmten Personen suchen',
    search_button: 'Suchen', search_results: 'Suchergebnisse für',
    no_results_found: 'Keine Ergebnisse gefunden', refresh: 'Aktualisieren',
    browse_description: 'Alle verarbeiteten Bilder durchsuchen', filter_options: 'Filteroptionen',
    filter_by_people: 'Nach Personen filtern', sort_by: 'Sortieren nach',
    sort_newest: 'Neueste zuerst', sort_oldest: 'Älteste zuerst',
    merge: 'Zusammenführen', select_all: 'Alle auswählen', deselect_all: 'Auswahl aufheben',
    batch_description: 'Gesamte Ordner verarbeiten', select_folder: 'Ordner wählen',
    recursive_scan: 'Unterordner einschließen', process_folder: 'Ordner verarbeiten',
    batch_progress: 'Fortschritt', batch_complete: 'Stapelverarbeitung abgeschlossen!',
    processed: 'Verarbeitet', failed: 'Fehlgeschlagen', skipped: 'Übersprungen', remaining: 'Verbleibend',
    stop_processing: 'Stopp', resume_processing: 'Fortsetzen',
    stats_overview: 'Übersicht', stats_total_people: 'Personen gesamt', stats_total_images: 'Bilder gesamt',
    stats_total_faces: 'Erkannte Gesichter', stats_database: 'Datenbank',
    refresh_stats: 'Aktualisieren',
    settings_title: 'Systemkonfiguration', recognition_settings: 'Erkennungseinstellungen',
    backend: 'Backend', model: 'Modell', detection_threshold: 'Erkennungsschwelle',
    recognition_threshold: 'Erkennungsschwellwert', use_gpu: 'GPU verwenden',
    ai_enrichment: 'KI-Anreicherung', enable_vlm: 'VLM aktivieren',
    vlm_provider: 'VLM-Anbieter', vlm_api_key: 'API-Schlüssel', vlm_model: 'Modell',
    ui_settings: 'Benutzeroberfläche', language: 'Sprache',
    save_settings: 'Einstellungen speichern', reset_settings: 'Zurücksetzen',
    user_management: 'Benutzerverwaltung', username: 'Benutzername', password: 'Passwort',
    role: 'Rolle', active: 'Aktiv', last_login: 'Letzter Login', actions: 'Aktionen',
    unidentified: 'Unbekannt',
    role_admin: 'Administrator', role_user: 'Benutzer',
    no_image: 'Bitte ein Bild hochladen', no_faces_detected: 'Keine Gesichter erkannt',
    settings_saved: 'Einstellungen gespeichert', error: 'Fehler', success: 'Erfolg',
    please_wait: 'Bitte warten...', loading: 'Lädt...', no_key: 'Kein Schlüssel', of: 'von',
    ok: 'OK', cancel: 'Abbrechen', save: 'Speichern', delete: 'Löschen', edit: 'Bearbeiten',
    view: 'Ansehen', download: 'Herunterladen', upload: 'Hochladen', clear: 'Leeren', reset: 'Zurücksetzen',
    confirm: 'Bestätigen', back: 'Zurück', next: 'Weiter', previous: 'Zurück',
    search_by_date: 'Datum',
    change_password: 'Passwort ändern',
    current_password: 'Aktuelles Passwort',
    new_password: 'Neues Passwort',
    confirm_password: 'Passwort bestätigen',
    password_changed: 'Passwort erfolgreich geändert',
    set_password: 'Passwort setzen',
    test_key: 'Testen',
    key_valid: 'Schlüssel gültig',
    key_invalid: 'Ungültiger Schlüssel',
    // Cloud drives
    cloud_drives: 'Cloud-Laufwerke',
    add_drive: 'Laufwerk hinzufügen',
    no_cloud_drives: 'Keine Cloud-Laufwerke konfiguriert',
    no_cloud_drives_hint: 'Netzwerkfreigabe oder Cloud-Konto hinzufügen',
    drive_name: 'Laufwerkname', drive_type: 'Typ', drive_host: 'Host', drive_server: 'Server',
    drive_share: 'Freigabe', drive_username: 'Benutzername', drive_password: 'Passwort',
    drive_domain: 'Domäne', drive_port: 'Port', drive_remote_path: 'Entfernter Pfad',
    drive_ssh_key: 'SSH-Schlüssel', drive_email: 'E-Mail', drive_tfa: '2FA-Code',
    drive_mount_point: 'Einhängepunkt', drive_read_only: 'Nur lesen',
    drive_scope: 'Bereich', drive_scope_system: 'System', drive_scope_user: 'Persönlich',
    drive_allowed_roles: 'Erlaubte Rollen', drive_auto_mount: 'Automatisch einbinden',
    drive_edit: 'Bearbeiten', drive_save: 'Laufwerk speichern', drive_delete: 'Laufwerk löschen',
    drive_delete_confirm: 'Laufwerk löschen?',
    drive_connect: 'Verbinden', drive_disconnect: 'Trennen',
    drive_mount: 'Einbinden', drive_unmount: 'Trennen', drive_test: 'Testen',
    drive_status_connected: 'Verbunden', drive_status_mounted: 'Eingebunden', drive_status_offline: 'Offline',
    drive_placeholder_name: 'Mein Laufwerk', drive_placeholder_host: 'z.B. 192.168.1.1',
    drive_placeholder_server: '//server/freigabe', drive_placeholder_share: 'freigabe',
    drive_placeholder_remote_path: '/entfernter/pfad', drive_placeholder_ssh_key: '/pfad/zum/schlüssel',
    drive_placeholder_tfa: '2FA-Code', drive_placeholder_mount_smb: '/mnt/smb',
    drive_placeholder_mount_sftp: '/mnt/sftp',
    // Face identification / clusters
    face_identification: 'Gesichtserkennung', face_clusters: 'Gesichtsgruppen',
    face_num: 'Gesicht #', identify_persons: 'Identifizieren',
    person_name_placeholder: 'Name eingeben…', type_name_placeholder: 'Name eingeben…',
    enter_person_name: 'Personenname eingeben',
    all_faces_identified: 'Alle Gesichter identifiziert', no_faces_in_image: 'Keine Gesichter in diesem Bild',
    no_clusters_found: 'Keine Gesichtsgruppen gefunden', no_clusters_detail: 'Weitere Bilder verarbeiten um Gesichtsgruppen zu erstellen',
    clustering_faces: 'Gesichter werden gruppiert…', similarity_threshold: 'Ähnlichkeitsschwelle',
    lower_threshold_hint: 'Niedrigerer Schwellwert = mehr Ergebnisse',
    recognition_certainty: 'Gewissheit', conf_short: 'Konf',
    clear_all_identifications: 'Alle Identifikationen löschen',
    clear_all_detections: 'Alle Erkennungen löschen',
    drag_to_mark_face: 'Ziehen um Gesicht zu markieren',
    // Train
    browse_button: 'Durchsuchen', train_folder_description: 'Ordner mit benannten Unterordnern (je eine Person)',
    // Sort options
    sort_date_taken_asc: 'Aufnahmedatum (älteste)', sort_date_taken_desc: 'Aufnahmedatum (neueste)',
    sort_filename_az: 'Dateiname A–Z', sort_most_faces: 'Meiste Gesichter',
    // Stats
    stats_images_with_date: 'Bilder mit Datum',
    // Lightbox / image ops
    zoom_in: 'Vergrößern', zoom_out: 'Verkleinern', fit_to_screen: 'Bildschirm füllen',
    press_esc_to_close: 'Esc zum Schließen', close: 'Schließen',
    run_detection: 'Erkennung starten', remove_detection: 'Erkennung entfernen',
    run_vlm_only: 'Nur VLM ausführen',
    min_face_size: 'Min. Gesichtsgröße',
    downsize_before_detect: 'Verkleinern auf (px)',
    downsize_before_vlm: 'Verkleinern vor VLM (px)',
    // Detection model labels
    det_model_auto: 'Auto (Standard)',
    det_model_retinaface: 'RetinaFace',
    det_model_scrfd: 'SCRFD',
    det_model_yunet: 'YuNet',
    det_model_mediapipe: 'MediaPipe',
    det_model_none: 'Keines (nur VLM)',
    vlm_prompt: 'Analysiere dieses Bild und gib an: 1. Eine kurze Beschreibung. 2. Den Szenentyp (z. B. Porträt, Landschaft usw.). 3. Eine Liste von Stichwort-Tags.',
    // API server + processing backend (v4)
    api_server_section:         'API / Datenbankserver',
    api_server_url_label:       'Server-URL',
    api_server_hint:            'URL, an die wir alle API-Aufrufe senden (Bilder, Personen, Gesichter, DB). Kann auf einen lokalen v4-Node.js, einen Remote-v2-FastAPI oder einen anderen Host zeigen. Die Verarbeitung läuft auf dem Server, der die API bedient.',
    api_server_connect:         'Verbinden',
    api_server_saved:           'Gespeicherte Server',
    api_server_save_as:         'Speichern als',
    api_server_preset_ph:       'Name des Eintrags…',
    api_server_save_preset:     'Speichern',
    processing_backend_section: 'Inferenz-Engine (Achse 3)',
    processing_backend_hint:    'Wo laufen Gesichtserkennung und Einbettung? Lokal = v4 Node.js ONNX. Remote v2 = Python/InsightFace auf separatem Server. Remote v4 = ONNX auf separatem v4-Server.',
    backend_local:              'Lokal (Node.js ONNX)',
    backend_remote_v2:          'Remote v2 Python FastAPI',
    backend_remote_v4:          'Remote v4 Node.js API',
    remote_v2_url:              'Remote-Server-URL',
    remote_v2_user:             'Benutzername',
    remote_v2_pass:             'Passwort',
    remote_v2_mode:             'Inferenz-Modus',
    remote_v2_upload_bytes:     'Bild hochladen → Inferenz auf Remote-Server',
    remote_v2_local_infer:      'Lokale Inferenz → nur Vektoren senden',
    remote_v2_test:             'Verbindung testen',
    remote_v2_connected:        'Verbunden',
    remote_v2_unreachable:      'Nicht erreichbar',
    pipeline_local:             'Lokal',
    pipeline_remote_v2:         'Remote v2',
    pipeline_remote_v4:         'Remote v4',
    // ONNX backend settings (browser)
    ort_browser_section:        'Inferenz-Provider',
    ort_browser_hint:           'Steuert, welche GPU/WASM-Backends onnxruntime-web nutzt. Wirksam nach Neuladen.',
    ort_use_simd:               'SIMD-Beschleunigung',
    ort_use_simd_hint:          'Schnelleres WASM (~2-4×). Experimentell – deaktivieren bei Abstürzen.',
    ort_use_webgl:              'WebGL-Beschleunigung',
    ort_use_webgl_hint:         'Nutzt GPU für Modell-Inferenz. Deaktivieren bei Abstürzen.',
    ort_use_webgpu:             'WebGPU (experimentell)',
    ort_use_webgpu_hint:        'Nächste GPU-Generation – Chrome 113+ / Edge. Fällt zurück auf WebGL/WASM.',
    // ONNX backend settings (server)
    ort_server_section:         'Server ONNX-Provider',
    ort_server_hint:            'Hardware-Beschleunigung für den Node.js-Face-Engine. Neustart erforderlich.',
    ort_use_coreml:             'CoreML (Apple Silicon / macOS)',
    ort_use_coreml_hint:        '~5-10× schneller auf Mac mit Apple Silicon.',
    ort_use_cuda:               'CUDA (NVIDIA GPU)',
    ort_use_cuda_hint:          'Erfordert CUDA Toolkit + GPU-Build von onnxruntime-node.',
    ort_use_directml:           'DirectML (Windows GPU)',
    ort_use_directml_hint:      'Hardware-Beschleunigung unter Windows für AMD/NVIDIA/Intel.',
    ort_recommended:            'Empfohlen für diese Plattform',
    ort_no_accel_available:     'Keine plattformspezifische Beschleunigung verfügbar (WASM-CPU).',
    settings_detectors:         'Detektoren',
    det_model_not_downloaded:   'Modell noch nicht heruntergeladen',
    det_lib_missing:            'Bibliothek fehlt',
    det_not_loaded:             'nicht geladen',
    det_model_corrupt:          'Modell beschädigt',
    // Generate / BFL
    gen_seed_random: 'zufällig',
    // Misc
    apply: 'Anwenden', apply_to_all: 'Auf alle anwenden', apply_to_selected: 'Auf Auswahl anwenden',
    skip: 'Überspringen', rescan: 'Neu scannen', scanning: 'Scannt…', save_all: 'Alle speichern',
    deselect: 'Auswahl aufheben', selection: 'Auswahl', source: 'Quelle', target: 'Ziel',
    search_name: 'Nach Name suchen…', operation_cancelled: 'Abgebrochen',
    people_detected: 'Erkannte Personen', process_more_images: 'Weitere Bilder verarbeiten',
    image_pending: '1 Bild ausstehend', images_pending: '{n} Bilder ausstehend',
    // Events
    photo: 'Foto', photos: 'Fotos', event_singular: 'Ereignis',
    events: 'Ereignisse', time_gap: 'Zeitabstand:', grouping_by_time: 'Gruppiere nach Zeit…',
    no_events_found: 'Keine Ereignisse gefunden. Bilder haben möglicherweise keine Datumsmetadaten.',
    event_name_placeholder: 'Ereignisname hinzufügen…', open_event: 'Ereignis öffnen →',
    // Identify
    all_faces: 'Alle Gesichter', no_images_with_faces: 'Keine Bilder mit erkannten Gesichtern.',
    // Watch Folders
    watch_folders: 'Überwachte Ordner', wf_path_placeholder: 'Ordnerpfad…',
    add: 'Hinzufügen', no_watch_folders: 'Noch keine überwachten Ordner.',
    no_watch_folders_sub: 'Oben einen Ordner hinzufügen, um neue Bilder automatisch einzulesen.',
    recursive: 'Rekursiv', auto_scan_label: 'Auto-Scan', every: 'Alle',
    files_added_stat: 'hinzugefügt', last_scan_time: 'Letzter Scan',
    scan_complete_msg: 'Scan abgeschlossen', scan_now: 'Jetzt scannen', auto_scan_every: 'Auto-Scan alle',
    wf_already_watched: 'Dieser Ordner wird bereits überwacht.',
    new_label: 'neu', found_label: 'gefunden', errors_label: 'Fehler',
    dismiss: 'Schließen', images_added_count: 'Bilder hinzugefügt.',
    // Duplicates
    duplicates: 'Duplikate', dup_method: 'Methode',
    dup_method_name_size: 'Dateiname + Größe', dup_method_hash: 'Binärer Hash (SHA256)',
    dup_method_visual: 'Visuell (pHash)', dup_threshold: 'Schwellwert',
    dup_keep: 'Behalten', dup_keep_most_faces: 'Meiste Gesichter',
    dup_keep_oldest: 'Älteste Datei', dup_keep_largest: 'Größte Datei',
    dup_action: 'Aktion', dup_delete_from_disk: 'Von Disk löschen',
    dup_remove_db_only: 'Nur aus DB entfernen', dup_replace_symlink: 'Durch Symlink ersetzen',
    dup_merge_faces: 'Gesichtszuweisungen zusammenführen', dup_resolve_selected: 'Ausgewählte auflösen',
    dup_resolving: 'Wird aufgelöst…', dup_resolved: '✓ Aufgelöst', dup_resolve: 'Auflösen',
    dup_role_guard: 'Duplikatauflösung erfordert Mediamanager- oder Admin-Zugriff',
    dup_view_only: 'Nur ansehen', no_duplicates: 'Keine Duplikate mit dieser Methode gefunden.',
    dup_run_scan_first: '"pHash scannen" oben zuerst ausführen.',
    dup_copies: 'Kopien', dup_groups: 'Gruppen', dup_keep_chip: '✓ Behalten', dup_del_chip: 'Löschen',
    computing_hashes: 'Berechne Hashes…',
    hash_scan_complete: 'Hash-Scan abgeschlossen — Duplikate aktualisiert',
    fill_hashes: 'Hashes befüllen', scanning_phash: 'Scanne pHash…',
    scan_phash_btn: 'pHash scannen', phash_scan_complete: 'pHash-Scan abgeschlossen',
    all_images_have_phash: 'Alle Bilder haben pHash',
    imagehash_not_installed: 'imagehash nicht auf dem Server installiert.',
    recoverable: 'rückgewinnbar',
    cleanup_source_files: 'Quelldateien bereinigen',
    cleanup_originals_hint: 'Diese Originale befinden sich außerhalb der Serverkopie — die serverseitige Datei wurde bereits behandelt. Wählen Sie, was mit den Originalen auf dem Quellrechner geschehen soll:',
    cleanup_action: 'Aktion', cleanup_trash_opt: 'In Papierkorb verschieben (reversibel)',
    cleanup_delete_opt: 'Dauerhaft löschen',
    cleanup_symlink_opt: 'Durch Symlink auf behaltene Datei ersetzen',
    download_script: 'Skript herunterladen', review_before_run: 'Vor der Ausführung prüfen',
    delete_via_browser: 'Über Browser löschen',
    browser_local_only: 'Erteilt Ordner-Berechtigung — nur lokale Dateien',
    move_to_trash: 'In Papierkorb verschieben',
    sends_to_os_trash: 'Verschiebt Dateien in den OS-Papierkorb (reversibel)',
    download_json_list: 'JSON-Liste herunterladen',
    import_to_local: 'In lokalen Electron-Client importieren, um Dateien dort zu entfernen',
    import_cleanup_json: 'Bereigung-JSON importieren',
    execute_downloaded_json: 'Zuvor heruntergeladene Bereinigung-JSON auf diesem Rechner ausführen',
    by_name_size: 'Nach Name+Größe:', by_hash: 'Nach Hash:', stat_visual: 'Visuell:',
    wasted: 'Verschwendet:', origin_label: 'Herkunft:',
    // Filesystem
    fs_server_mode: 'Server', fs_local_mode: 'Lokal', fs_cloud_mode: 'Cloud',
    select_drive_below: 'Unten ein Laufwerk auswählen',
    fs_in_db: 'In DB', fs_not_in_db: 'Nicht in DB', fs_no_images: 'keine Bilder',
    fs_folder_label: 'Ordner', fs_image_label: 'Bild', fs_file_label: 'Datei',
    fs_empty_folder: 'Dieser Ordner ist leer.',
    fs_name_col: 'Name', fs_status_col: 'Status', fs_size_col: 'Größe',
    fs_fetching: 'Wird abgerufen', fs_uploading: 'Wird hochgeladen', fs_adding: 'Wird hinzugefügt',
    fs_images_only: '(nur Bilder)', fs_images_folders: '(Bilder + Ordner)',
    fs_already_in_db: 'bereits in DB.', fs_go: 'Los', fs_path_placeholder: 'Pfad eingeben…',
    fs_select_cloud_drive: 'Cloud- oder Netzlaufwerk zum Durchsuchen auswählen:',
    fs_no_cloud_drives_fs: 'Keine Cloud-Laufwerke konfiguriert.',
    fs_add_in_settings: 'Laufwerke in Einstellungen → Cloud-Laufwerke hinzufügen.',
    fs_grant_access: 'Zugriff auf Ordner gewähren…',
    fs_pick_local_folder: 'Lokalen Ordner auswählen — fragt nach Berechtigung.',
    fs_select_images: 'Bilder auswählen…', fs_select_folder_btn: 'Ordner auswählen…',
    fs_rename: 'Umbenennen', fs_trash: 'Papierkorb', fs_loading_drives: 'Laufwerke laden…',
    fs_not_connected: 'Nicht verbunden — zuerst in Cloud-Laufwerken verbinden',
    fs_add_to_db: 'Zur DB hinzufügen', fs_add_to_db_cloud: 'Von Cloud zur DB hinzufügen',
    fs_upload_to_db: 'Zur DB hochladen', fs_shared: 'Geteilt', fs_private: 'Privat',
    fs_select_drive_to_add: 'Bilder oder Ordner auswählen, um zur DB hinzuzufügen',
    fs_upload_to_server: 'Bilder hochladen, um sie zur Server-DB hinzuzufügen',
    fs_change_folder: 'Ordner ändern…',
    fs_local_folder_hint: 'Lokaler Ordner — "Zugriff gewähren" klicken, um Gerät zu durchsuchen',
    fs_local_upload_hint: 'Lokales Hochladen — Bilder oder Ordner vom Gerät auswählen',
    // Context menu
    ctx_open_external: 'Datei öffnen', ctx_open_folder: 'Ordner öffnen',
    ctx_browse_folder: 'Ordner durchsuchen', ctx_add_to_album: 'Zum Album hinzufügen',
    ctx_no_albums: 'Keine Alben — erst eines erstellen', ctx_new_album: '+ Neues Album…',
    ctx_people_in_image: 'Personen in diesem Bild', ctx_all_photos_of: 'Alle Fotos von',
    ctx_crop_image: 'Bild zuschneiden', ctx_adjust_image: 'Bild anpassen',
    ctx_convert_export: 'Konvertieren / Exportieren', ctx_download_file: 'Datei herunterladen',
    ctx_copy_path: 'Dateipfad kopieren',
    // Convert modal
    conv_format: 'Format', conv_quality: 'Qualität', conv_resize: 'Skalieren',
    conv_no_resize: 'Keine Skalierung', conv_fit: 'Einpassen (Seitenverhältnis beibehalten)',
    conv_exact: 'Genaue Abmessungen', conv_max_size: 'Maximale Größe', conv_save_as: 'Speichern als',
    conv_replace_orig: 'Original ersetzen', conv_new_file: 'Neue Datei',
    conv_output_folder: 'Ausgabeordner', conv_suffix: 'Suffix', conv_folder: 'Ordner',
    conv_done: 'Fertig', conv_converting: 'Konvertiere…', conv_convert: 'Konvertieren',
    // Adjust modal
    adj_input_levels: 'Eingabepegel', adj_output: 'Ausgabe', adj_presets: 'Voreinstellungen',
    adj_light: 'Licht', adj_brightness: 'Helligkeit', adj_contrast: 'Kontrast',
    adj_colour: 'Farbe', adj_saturation: 'Sättigung', adj_warmth: 'Wärme',
    adj_detail: 'Detail', adj_sharpness: 'Schärfe', adj_save_as: 'Speichern als',
    adj_replace_orig: 'Original ersetzen', adj_new_file: 'Neue Datei', adj_suffix: 'Suffix',
    adj_applying: 'Wird angewendet…', adj_reset_all: 'Alles zurücksetzen', adj_saved: '✓ Gespeichert',
    selected_label: 'ausgewählt',
    // BFL AI-Bildbearbeitung
    bfl_outpaint: 'Ausmalen', bfl_inpaint: 'Einmalen', bfl_ai_edit: 'KI-Bearbeitung',
    bfl_add_top: 'Oben hinzufügen', bfl_add_bottom: 'Unten hinzufügen',
    bfl_add_left: 'Links hinzufügen', bfl_add_right: 'Rechts hinzufügen',
    bfl_mask_x: 'Maske X', bfl_mask_y: 'Maske Y',
    bfl_mask_w: 'Maske Breite', bfl_mask_h: 'Maske Höhe',
    bfl_prompt_optional: 'Prompt (optional)',
    bfl_edit_prompt: 'Bearbeitung beschreiben…',
    bfl_inpaint_prompt: 'Was im markierten Bereich erzeugen…',
    bfl_model: 'Modell',
    bfl_applying: 'Wird generiert…', bfl_done: '✓ Generiert',
    bfl_no_key: 'BFL-API-Schlüssel fehlt — in Einstellungen → API-Schlüssel hinzufügen',
    ctx_ai_edit: 'KI-Bearbeitung (BFL)',
    conv_resize_outpaint: 'Ausmalen (KI)',
    bfl_generate: 'Generieren',
    bfl_gen_prompt: 'Was generiert werden soll…',
    bfl_aspect_ratio: 'Seitenverhältnis',
    bfl_output_folder: 'Ausgabeordner',
    bfl_filename_prefix: 'Dateinamen-Präfix',
    bfl_gen_hint: 'Vorschau nur zur Referenz — wird nicht an das Modell gesendet',
    bfl_gen_hint_include: 'Vorschau — wird als Eingabebild gesendet',
    bfl_include_ref_image: 'Als Referenzbild einschließen (input_image)',
    bfl_width: 'Breite (px)',
    bfl_height: 'Höhe (px)',
    bfl_steps: 'Schritte',
    bfl_guidance: 'Führung',
    bfl_seed: 'Zufallswert',
    bfl_zoom: 'Zoom',
    bfl_drag_hint: 'Ränder ziehen um Randgröße festzulegen',
    bfl_mask_hint: 'Ziehen um den Füllbereich zu positionieren',
    // Sidebar nav labels
    tab_albums: 'Alben',
    tab_events: 'Ereignisse',
    tab_identify: 'Identifizieren',
    tab_faceclusters: 'Gesichtsgruppen',
    tab_filesystem: 'Dateisystem',
    tab_watchfolders: 'Überwachte Ordner',
    tab_duplicates: 'Duplikate',
    tab_ingest: 'Import',
    sidebar_expand: 'Seitenleiste ausklappen',
    sidebar_collapse: 'Seitenleiste einklappen',
    tab_about: 'Über CrispLens',
    tab_privacy: 'Datenschutz',
    legal_imprint: 'Impressum / Rechtliches',
    // Crop / Canvas Size modal
    tab_generate: 'Generieren',
    crop_image: 'Bild zuschneiden',
    canvas_size: 'Leinwandgröße',
    crop_aspect_ratio: 'Seitenverhältnis',
    crop_selection_px: 'Auswahl (px)',
    crop_reset: '↺ Zurücksetzen',
    crop_filename_hint: 'Dateiname (leer = automatisch)',
    crop_and_save: 'Zuschneiden & Speichern',
    saving: 'Speichern…',
    save_as: 'Speichern als',
    save_as_replace: 'Original ersetzen',
    save_as_new_file: 'Neue Datei',
    canvas_add_border: 'Rand hinzufügen (px)',
    canvas_fill_mode: 'Füllmodus',
    canvas_fill_solid: 'Volltonfarbe',
    canvas_fill_mirror: 'Randpixel spiegeln',
    canvas_fill_outpaint: 'KI-Outpaint',
    canvas_fill_outpaint_hint: 'Öffnet KI-Bearbeitung → Outpaint-Tab',
    canvas_apply: 'Leinwandgröße anwenden',
    // Generate view
    gen_image_title: 'Bild generieren',
    gen_model_label: 'Modell',
    gen_prompt_label: 'Prompt',
    gen_prompt_placeholder: 'Was generiert werden soll…',
    gen_filename_prefix: 'Dateinamen-Präfix',
    gen_output_folder: 'Ausgabeordner (optional)',
    gen_output_folder_hint: 'Leer lassen für Standard-Ordner generated/',
    gen_result_title: 'Generiertes Bild',
    gen_view_in_gallery: 'In Galerie ansehen',
    gen_generating: 'Wird generiert…',
    // Done-panel actions (shared between AIEditModal and GenerateView)
    done_without_db: 'Ohne DB',
    done_view_raw: 'Ansehen (kein DB)',
    done_download_raw: 'Download (kein DB)',
    done_save_to_db: 'In DB speichern',
    done_save_only: 'Nur speichern',
    done_save_gallery_title: 'In DB eintragen und in Galerie anzeigen',
    done_save_lightbox_title: 'In DB eintragen und Bild öffnen',
    done_save_silent_title: 'In DB eintragen und schließen',
    done_generate_another: 'Nochmals generieren',
    // Detection model selector (shared)
    rescan_mode_both: 'Beides', rescan_mode_faces: 'Gesichter', rescan_mode_vlm: 'VLM',
    also_run_vlm: 'Auch VLM aktualisieren',
    // Settings — section titles + labels
    settings_server_section:    'Node.js-Server',
    settings_mode_run_local:    'Lokal auf diesem Rechner ausführen',
    settings_mode_run_local_hint:'App verwaltet eigenen Node.js/Express-Server (kein Python erforderlich)',
    settings_mode_remote:       'Mit Remote-Server verbinden (VPS)',
    settings_mode_remote_hint:  'Verbindung zu CrispLens v4 Node.js oder v2 FastAPI',
    settings_server_restart_hint:'Änderungen am Server-Modus erfordern einen Neustart.',
    settings_restart_wasm:      'WASM-Engine neu starten',
    settings_local_port:        'Lokaler Port',
    settings_server_url:        'Server-URL',
    settings_db_section:        'Datenbank',
    settings_db_switch_hint:    'Zwischen lokalen SQLite-Datenbankdateien wechseln. Erfordert Neustart.',
    settings_db_current:        'Aktuelle DB',
    settings_db_switch_to:      'Wechseln zu',
    settings_db_switch_btn:     'Datenbank wechseln & Neustart',
    settings_db_remote_info:    'Datenbank wird vom Remote-Server verwaltet.',
    settings_img_proc_section:  'Bildverarbeitung',
    settings_python_path:       'Python-Pfad',
    settings_upload_mode:       'Bilder auf Server hochladen',
    settings_upload_mode_hint:  'Lokale Bilder an VPS senden — Server führt InsightFace + VLM aus',
    settings_local_proc_mode:   'Lokal verarbeiten, Ergebnisse hochladen',
    settings_local_proc_mode_hint:'InsightFace lokal ausführen → nur Embeddings + Thumbnail hochladen (kein VLM)',
    settings_local_model:       'Lokales Modell',
    settings_det_size:          'Erkennungsgröße',
    settings_det_size_hint:     'Größere Werte erkennen kleinere Gesichter, sind aber langsamer.',
    settings_storage_section:   'Speicher',
    settings_storage_hint:      'Maximale Bildgröße nach dem Hochladen begrenzen. Spart Speicherplatz, wenn Originale lokal bleiben.',
    settings_upload_max_dim:    'Max. Auflösung beim Hochladen (px)',
    settings_no_resize:         'Volle Auflösung (keine Größenänderung)',
    settings_resize_hint:       'Bilder werden vor dem Speichern skaliert',
    settings_db_health:         'Datenbank-Diagnose',
    db_path_label:              'Pfad',
    db_size_label:              'Größe',
    db_writable_label:          'Beschreibbar',
    db_users_label:             'Benutzer',
    db_images_label:            'Bilder',
    hard_reset_app:             'Einstellungen zurücksetzen (Sicher)',
    reload_after_settings:      'Seite nach dem Ändern dieser Einstellungen neu laden.',
    settings_engine_section:    'Gesichtserkennungs-Engine',
    settings_engine_ready:      '✓ Bereit',
    settings_engine_not_ready:  '✗ Nicht bereit',
    settings_reload_engine:     'Engine neu laden',
    detection_model:            'Erkennungsmodell',
    det_model_global_hint:      'Globale Voreinstellung',
    add_user:                   'Benutzer hinzufügen',
    settings_db_backup_title:   'Standalone-Backup & Portabilität',
    settings_db_backup_hint:    'Nutzen Sie diese Optionen, um Ihre Daten zwischen lokaler Nutzung bzw. Geräten zu verschieben.',
    settings_db_export:         'Datenbank exportieren',
    settings_db_import:         'Datenbank importieren',
    settings_db_clear:          'Alles löschen',
    settings_db_clear_confirm:  'Dies wird alle Bilder, Personen und Einstellungen aus Ihrer lokalen Datenbank löschen. KANN NICHT RÜCKGÄNGIG GEMACHT WERDEN. Fortfahren?',
    settings_db_import_confirm: 'Das Importieren wird vorhandene Daten überschreiben oder zusammenführen. Fortfahren?',
    // Admin — server management
    admin_server_mgmt:   'Server-Verwaltung',
    admin_update_server: 'Server aktualisieren',
    admin_view_logs:     'Logs anzeigen',
    admin_run_update:    'Update starten',
    update_modal_hint:   'Führt fix_db.sh als root aus (git pull + DB-Migrationen + Neustart). Die Verbindung wird beim Neustart unterbrochen.',
    root_password:       'Root-Passwort',
    running:             'Läuft…',
    admin_logs_title:    'Server-Logs',
    logs_refresh:        'Aktualisieren',
    logs_follow:         'Folgen',
    logs_path:           'Log-Datei',
    // Admin — copy-exempt paths
    exempt_paths_label:  'Kopier-Ausnahmepfade',
    exempt_paths_hint:   'Dateien von diesen Server-Pfaden werden direkt in der DB registriert (keine Kopie nach uploads/).',
    fix_db_path_label:   'fix_db.sh Pfad',
    fix_db_path_hint:    'Vollständiger Pfad zu fix_db.sh auf dem Server.',
    // ProcessView — mode badges, controls, drop zone, server folder, detection settings
    pv_mode_local:             'Lokal',
    pv_mode_upload:            'Hochladen',
    pv_mode_web_infer:         'Browser-Inferenz',
    pv_web_local_infer:        'Lokale Inferenz',
    pv_web_local_infer_hint:   'Erkennung & Einbettung lokal via ONNX — nur Vektoren werden gesendet. Beim ersten Start werden Modelle heruntergeladen (~180 MB, danach gecacht).',
    pv_clear_done:             'Fertige entfernen',
    pv_clear_all:              'Alle entfernen',
    pv_local_base_label:       'Lokaler Basisordner (optional):',
    pv_local_base_placeholder: '/Users/alice/Bilder',
    pv_local_base_hint:        'Wird Dateinamen vorangestellt, wenn vollständiger Pfad nicht anzeigbar',
    pv_local_path_notice:      'Lokaler Basisordner wird für Stapelaufträge benötigt',
    pv_drop_active:            'Ablegen um zur Warteschlange hinzuzufügen',
    pv_drop_idle:              'Bilder oder Ordner hier ablegen',
    pv_drop_sub:               'Mehrere Dateien möglich · JPEG, PNG, WebP, …',
    pv_select_files:           'Dateien auswählen…',
    pv_select_folder_btn:      'Ordner auswählen…',
    pv_item:                   'Element',
    pv_items:                  'Elemente',
    pv_pending:                'ausstehend',
    pv_process_btn:            '▶ Verarbeiten',
    pv_process_direct:         'Direkt',
    pv_process_direct_hint:    'Dateien jetzt in der lokalen Warteschlange verarbeiten (nicht persistent)',
    pv_process_as_batch:       'Als Stapel',
    pv_uploading_progress:     'Hochladen {n} / {total}…',
    pv_image:                  'Bild',
    pv_images:                 'Bilder',
    pv_server_folder_label:    'Oder Server-Ordner direkt verarbeiten',
    pv_server_folder_ph:       '/data/fotos  (Pfad auf dem VPS)',
    pv_browse:                 'Durchsuchen…',
    pv_subfolders:             'Unterordner',
    pv_det_settings:           'Erkennungseinstellungen',
    pv_skip_faces:             'Gesichtserkennung überspringen',
    pv_skip_vlm:               'KI-Beschreibung überspringen (VLM)',
    pv_max_size_label:         'Verkleinern auf (px)',
    pv_max_size_hint:          '0 = Original',
    pv_already_uploaded:       'bereits hochgeladen',
    pv_shared_by_others:       'von anderen geteilt',
    pv_badge_pending:          'ausstehend',
    pv_badge_processing:       'Verarbeitung…',
    pv_badge_error:            'Fehler',
    pv_own_dup_title:          'Bereits von Ihnen hochgeladen',
    pv_shared_dup_title:       'Gleicher Inhalt bereits von einem anderen Benutzer hochgeladen',
    pv_remove:                 'Entfernen',
    pv_vlm_desc_received:      'VLM-Beschreibung empfangen',
    pv_vlm_tags_received:      'VLM-Tags empfangen',
    pv_faces_identified:       'Gesichter identifiziert',
    pv_matched_in_index:       'Im Index gefunden',
    pv_dup_mode_label:         'Duplikate',
    pv_dup_mode_skip:          'Überspringen (nicht neu verarbeiten)',
    pv_dup_mode_overwrite:     'Überschreiben (neu verarbeiten, gleiche Zeile)',
    pv_dup_mode_add:           'Immer hinzufügen (Duplikate ignorieren)',
    pv_dup_skipped:            'übersprungen (Duplikat)',

    // Standalone / Storage mode
    settings_storage_mode:     'Datenquelle (Achse 1)',
    settings_storage_mode_hint: 'Woher kommen Bild-/Personendaten? Server verbindet sich mit einem v4 Node.js oder v2 FastAPI Backend (Achse 2 legt fest, welches). Standalone verwendet SQLite auf dem Gerät — kein Server erforderlich.',
    settings_standalone_active: '⚡ Standalone-Modus aktiv. Gesichtserkennung läuft lokal mit den unten zwischengespeicherten ONNX-Modellen. Cloud-VLM-Anreicherung (optional) ruft externe API-Anbieter direkt auf – kein Server erforderlich.',
    settings_sync_target:      'Synchronisierungsziel',
    settings_sync_target_hint: 'Legen Sie den Remote-Server fest, von dem Daten im Standalone-Modus gesendet/empfangen werden sollen.',
    settings_det_retries:      'Erkennungs-Wiederholungen',
    settings_det_retries_hint: 'Fallback-Versuche mit niedrigerer Schwelle, wenn keine Gesichter gefunden wurden',
    settings_model_cached:     'gecached',
    settings_model_not_found:  'nicht heruntergeladen',
    settings_models_download_hint: 'Modelle werden vom verbundenen Server heruntergeladen und auf dem Gerät gespeichert (~185 MB insgesamt). Einmal online herunterladen, dann für immer offline nutzen.',
    settings_db_diag:          'Datenbank-Diagnose',
    settings_engine_status:    'Face Recognition Engine',
    settings_engine_backend:   'Backend',
    settings_engine_model:     'Modell',
    settings_transport_diag:   'SSE / Transport-Diagnose',

    pv_tags_label:             'Tags',
    pv_tags_placeholder:       'Tag wählen oder eingeben…',
    pv_album_label:            'Album',
    pv_album_placeholder:      'Album wählen oder eingeben…',
    pv_album_new_prefix:       'Erstellen:',
    pv_creator_label:          'Urheber',
    pv_creator_placeholder:    'Urhebername…',
    pv_copyright_label:        'Copyright',
    pv_copyright_placeholder:  '© 2025 Name…',
    pv_submit_batch_job:       'Stapelauftrag erstellen',
    pv_follow_symlinks:        'Symlinks folgen',

    // Archive metadata fields (MetaPanel)
    archive_metadata:            'Archiv-Metadaten',
    arch_fachbereich:            'Fachbereich',
    arch_veranstaltungsnummer:   'Veranstaltungsnummer',
    arch_datum:                  'Datum',
    arch_veranstaltungstitel:    'Veranstaltungstitel',
    arch_urheber:                'Urheber',

    tab_batchjobs:             'Stapelaufträge',
    bj_title:                  'Stapelaufträge',
    bj_no_jobs:                'Noch keine Stapelaufträge.',
    bj_no_jobs_hint:           'In Verarbeiten → Server-Ordner erstellen.',
    bj_status_pending:         'Ausstehend',
    bj_status_running:         'Läuft',
    bj_status_paused:          'Pausiert',
    bj_status_cancelled:       'Abgebrochen',
    bj_status_done:            'Abgeschlossen',
    bj_status_error:           'Fehler',
    bj_start:                  'Starten',
    bj_resume:                 'Fortsetzen',
    bj_cancel:                 'Abbrechen',
    bj_delete:                 'Löschen',
    bj_view_logs:              'Logs anzeigen',
    bj_logs_title:             'Fehlerprotokoll',
    bj_logs_empty:             'Keine Fehler.',
    bj_logs_save:              'Log herunterladen',
    bj_source:                 'Quelle',
    bj_created:                'Erstellt',
    bj_total:                  'Gesamt',
    bj_done:                   'Fertig',
    bj_errors:                 'Fehler',
    bj_delete_confirm:         'Auftrag und Protokoll löschen?',
    bj_cancel_confirm:         'Laufenden Auftrag abbrechen?',
    bj_file_inaccessible:      'Datei nicht erreichbar',
    bj_enum_started:           'Dateien werden aufgelistet…',
    bj_show_all_users:         'Alle Benutzer anzeigen (Admin)',
    bj_tags_applied:           'Tags',
    bj_album_applied:          'Album',
    bj_progress:               'Fortschritt',
    bj_name:                   'Name',
    bj_retry:                  'Fehlgeschlagene erneut versuchen',
    bj_persistent_hint:        'Einen dauerhaften serverseitigen Auftrag für diese Dateien erstellen',
    bj_source_selection:       'Manuelle Auswahl',

    // Offline / local cache
    offline_cache_section:     'Offline-Cache',
    offline_cache_hint:        'Lade die neuesten Bilder und Thumbnails für die Offline-Nutzung herunter.',
    offline_max_images:        'Max. gecachte Bilder',
    offline_max_size_mb:       'Max. Cache-Größe (MB)',
    offline_sync_btn:          'Jetzt synchronisieren',
    offline_syncing:           'Synchronisiere…',
    offline_clear:             'Cache leeren',
    offline_stats_images:      'Bilder gecacht',
    offline_stats_size:        'MB belegt',
    offline_last_sync:         'Letzte Synchronisierung:',
    offline_never_synced:      'Noch nicht synchronisiert',
    offline_phase_metadata:    'Metadaten laden…',
    offline_phase_thumbnails:  'Thumbnails cachen',
    offline_phase_done:        'Synchronisierung abgeschlossen',
    offline_cleared:           'Cache geleert',
    offline_banner:            '⚡ Offline — zeige gecachte Daten',
    offline_thumb_size:        'Vorschaugröße',
    offline_thumb_size_hint:   'Bestimmt die Auflösung der Vorschaubilder für den Offline-Modus UND die Auflösung der im Browser gespeicherten Standalone-Bilder.',
    offline_pending_push:      'Element(e) zum Hochladen in Warteschlange',
    offline_push_btn:          'Jetzt hochladen',
    offline_push_hint:         'Lokal verarbeitete Bilder auf den Server hochladen',
    offline_pushing:           'Hochladen…',
    pv_queued_offline:         'In Warteschlange — wird synchronisiert wenn online',
    pv_local_pick_title:       'Fotos aus Bibliothek auswählen',
    pv_local_pick_sub:         'Gesichtserkennung läuft auf dem Gerät — kein Server nötig',
    pv_local_pick_btn:         'Fotos auswählen',
    // Axis / Settings strings
    axis_title: 'Verbindung & Inferenz',
    axis_subtitle: 'Drei unabhängige Einstellungen steuern die Arbeitsweise von CrispLens.',
    axis_1_label: 'Datenquelle (Achse 1)',
    axis_1_hint: 'Woher kommen Bild-/Personendaten? Server verbindet sich mit einem v4-Node.js oder v2-FastAPI Backend (Achse 2 legt fest, welches). Standalone verwendet SQLite auf dem Gerät — kein Server erforderlich.',
    axis_1_isolation: 'Daten-Isolation: Server- und Standalone-Modus verwenden getrennte Datenbanken. Die lokale .db-Datei wird nur im Server-Modus verwendet. Im Standalone-Modus werden Daten ausschließlich in der IndexedDB (WASM) Ihres Browsers gespeichert.',
    axis_1_server: 'Server',
    axis_1_server_desc: 'v4 Node.js oder v2 FastAPI',
    axis_1_standalone: 'Standalone (Lokal)',
    axis_1_standalone_desc: 'SQLite auf dem Gerät (WASM), kein Server erforderlich',
    axis_2_label: 'API / Datenbankserver',
    axis_2_hint: 'URL, an die wir alle API-Aufrufe senden (Bilder, Personen, Gesichter, DB). Kann auf einen lokalen v4-Node.js, einen Remote-v2-FastAPI oder einen anderen Host zeigen. Die Verarbeitung läuft auf dem Server, der die API bedient.',
    axis_3_label: 'Inferenz-Engine (Achse 3)',
    axis_3_current: 'Aktuell:',
    bench_title: 'Benchmark',
    bench_hint: 'Testen Sie die Leistung verschiedener Inferenz-Backends auf diesem Gerät.',
    bench_run: 'Browser-Benchmark starten',
    api_keys_section: 'API-Schlüssel',
    api_keys_regular_user: 'Als regulärer Benutzer haben Sie nur Zugriff auf in der EU gehostete Anbieter.',
    ai_enrichment_override: 'Persönliche Einstellung — globale Voreinstellung:',
  },
};
// -- Initial language logic ---------------------------------------------------
function _getInitialLanguage() {
  const stored = localStorage.getItem('pwa_language');
  if (stored) {
    console.log(`[stores] Found stored language in localStorage: "${stored}"`);
    return stored;
  }
  try {
    const cached = JSON.parse(sessionStorage.getItem('i18n_cache'));
    if (cached && (cached.language || cached.lang)) {
      const l = cached.language || cached.lang;
      console.log(`[stores] Found cached language in sessionStorage: "${l}"`);
      return l;
    }
  } catch (e) {}
  console.log('[stores] No stored language found, defaulting to "en"');
  return 'en';
}

function _getInitialTranslations(l) {
  const base = EN; // defined above
  const target = (TRANSLATIONS && TRANSLATIONS[l]) ? TRANSLATIONS[l] : {};
  console.log(`[stores] Initializing translations for "${l}". Target keys: ${Object.keys(target).length}`);
  return { ...base, ...target };
}

const _initLang = _getInitialLanguage();
const _initStrings = _getInitialTranslations(_initLang);


export const translations = writable(_initStrings);
export const lang = writable(_initLang);

export const t = derived(translations, $t => (key) => $t[key] || key);

// ── Watch folders ──────────────────────────────────────────────────────────────
export const watchFolders = writable([]);

// ── Filesystem browser ──────────────────────────────────────────────────────
export const fsCurrentPath = writable('');

// ── Albums ───────────────────────────────────────────────────────────────────
export const allAlbums = writable([]);

// ── Ratings & flags ──────────────────────────────────────────────────────────
// Local cache of user-assigned ratings/flags; key = image_id (number)
export const starRatings = writable({});   // { [id]: 0-5 }
export const colorFlags  = writable({});   // { [id]: 'pick'|'delete'|null }

// ── Lightbox refresh ─────────────────────────────────────────────────────────
// Increment to force the lightbox to reload its image (e.g., after rotate)
export const lightboxKey = writable(0);

// ── Gallery refresh tick ──────────────────────────────────────────────────────
// Increment to trigger a gallery reload (e.g., after upload completion)
export const galleryRefreshTick = writable(0);

// ── Background task (e.g., "Add to DB" SSE) ──────────────────────────────────
// { label: string, done: number, total: number } | null
export const backgroundTask = writable(null);

// ── Hybrid ingest mode (when Electron is connected to a remote VPS) ───────────
// 'upload_full'    — Electron uploads full images → VPS processes (default)
// 'local_process'  — Electron runs InsightFace → uploads embeddings only
export const processingMode   = writable('upload_full');
export const localModel       = writable('buffalo_l');
export const localModelStatus = writable({});   // { buffalo_l: bool, ... }

// ── Processing backend (v4) ────────────────────────────────────────────────────
// 'local'      — Node.js ONNX (SCRFD + YuNet)
// 'remote_v2'  — Route to remote v2 FastAPI server (Python pipeline)
// 'remote_v4'  — Route to remote v4 Node.js API server (SCRFD + YuNet)
// Axis 3 of the three-axis model. Persisted in localStorage key 'crisp_processing_backend'
// so it is available regardless of which server (or no server) is currently connected.
export const processingBackend = writable(
  (typeof window !== 'undefined' && localStorage.getItem('crisp_processing_backend')) || 'local'
);

// ── Derived ───────────────────────────────────────────────────────────────────
export const activeFilterCount = derived(filters, $f => {
  return Object.entries($f)
    .filter(([key, val]) => key !== 'searchFields' && val && typeof val === 'string' && val.trim())
    .length;
});

// True when the app is in standalone (local WASM) mode but the v4 server is
// reachable yet has no valid session — cloud drives / filesystem need a login.
export const serverLoginNeeded = writable(false);
